// GERADO POR scripts/construir-catalogo.mjs — não edite à mão.
// Só os clubes em uso pelos jogadores; o catálogo completo, para consultar
// ao escrever uma carreira nova, está em scripts/catalogo-completo.json.
// Nome e id dos clubes usados pelos jogadores vivem em scripts/clubes-canonicos.mjs.
import type { Clube } from './tipos'

export const CLUBES: Clube[] = [
  { id: 'aarhus-gf', nome: "Aarhus GF", pais: 'DK', escudo: 'aarhus-gf.png' },
  { id: 'abc', nome: "ABC", pais: 'BR', escudo: 'abc.svg' },
  { id: 'acr-siena-1904', nome: "ACR Siena 1904", pais: 'IT', escudo: 'acr-siena-1904.png' },
  { id: 'adana-demirspor', nome: "Adana Demirspor", pais: 'TR', escudo: 'adana-demirspor.png' },
  { id: 'ajax', nome: "Ajax", pais: 'NL', escudo: 'ajax.png' },
  { id: 'al-ahli-emirados-arabes-unidos', nome: "Al-Ahli Dubai", pais: 'AE', escudo: 'al-ahli-emirados-arabes-unidos.png' },
  { id: 'al-ahli-saudi', nome: "Al-Ahli", pais: 'SA', escudo: 'al-ahli-saudi.png' },
  { id: 'al-ahli-sports-club', nome: "Al-Ahli Doha", pais: 'QA', escudo: 'al-ahli-sports-club.png' },
  { id: 'al-arabi-sports-club', nome: "Al-Arabi", pais: 'QA', escudo: 'al-arabi-sports-club.png' },
  { id: 'al-ettifaq', nome: "Al-Ettifaq", pais: 'SA', escudo: 'al-ettifaq.svg' },
  { id: 'al-gharafa', nome: "Al-Gharafa", pais: 'QA', escudo: 'al-gharafa.png' },
  { id: 'al-hilal', nome: "Al-Hilal", pais: 'SA', escudo: 'al-hilal.svg' },
  { id: 'al-ittihad', nome: "Al-Ittihad", pais: 'SA', escudo: 'al-ittihad.svg' },
  { id: 'al-jaish-qatar', nome: "Al-Jaish", pais: 'QA', escudo: 'al-jaish-qatar.png' },
  { id: 'al-jazira', nome: "Al-Jazira", pais: 'AE', escudo: 'al-jazira.png' },
  { id: 'al-kholood', nome: "Al-Kholood", pais: 'SA', escudo: 'al-kholood.svg' },
  { id: 'al-khor-sports-club', nome: "Al-Khor", pais: 'QA', escudo: 'al-khor-sports-club.png' },
  { id: 'al-nasr-sports-club', nome: "Al-Nasr Dubai", pais: 'AE', escudo: 'al-nasr-sports-club.png' },
  { id: 'al-nassr', nome: "Al-Nassr", pais: 'SA', escudo: 'al-nassr.svg' },
  { id: 'al-qadsiah', nome: "Al-Qadsiah", pais: 'SA', escudo: 'al-qadsiah.svg' },
  { id: 'al-rayyan-sports-club', nome: "Al-Rayyan", pais: 'QA', escudo: 'al-rayyan-sports-club.png' },
  { id: 'al-sadd-sports-club', nome: "Al-Sadd", pais: 'QA', escudo: 'al-sadd-sports-club.png' },
  { id: 'al-shabab', nome: "Al-Shabab", pais: 'SA', escudo: 'al-shabab.svg' },
  { id: 'al-wahda-sports-cultural-club', nome: "Al-Wahda", pais: 'AE', escudo: 'al-wahda-sports-cultural-club.png' },
  { id: 'al-wakrah-sports-club', nome: "Al-Wakrah", pais: 'QA', escudo: 'al-wakrah-sports-club.png' },
  { id: 'albacete', nome: "Albacete", pais: 'ES', escudo: 'albacete.svg' },
  { id: 'albirex-niigata', nome: "Albirex Niigata", pais: 'JP', escudo: 'albirex-niigata.svg' },
  { id: 'alfreton-town-football-club', nome: "Alfreton Town", pais: 'EN', escudo: 'alfreton-town-football-club.png' },
  { id: 'america', nome: "america", pais: 'MX', escudo: 'america.png' },
  { id: 'america-football-club-rio-de-janeiro', nome: "America-RJ", pais: 'BR', escudo: 'america-football-club-rio-de-janeiro.svg' },
  { id: 'america-futebol-clube-belo-horizonte', nome: "América-MG", pais: 'BR', escudo: 'america-futebol-clube-belo-horizonte.png' },
  { id: 'america-futebol-clube-rio-grande-do-norte', nome: "América-RN", pais: 'BR', escudo: 'america-futebol-clube-rio-grande-do-norte.svg' },
  { id: 'anapolis-futebol-clube', nome: "Anápolis", pais: 'BR', escudo: 'anapolis-futebol-clube.png' },
  { id: 'antalyaspor', nome: "Antalyaspor", pais: 'TR', escudo: 'antalyaspor.png' },
  { id: 'arsenal', nome: "Arsenal", pais: 'EN', escudo: 'arsenal.svg' },
  { id: 'associacao-atletica-internacional-limeira', nome: "Inter de Limeira", pais: 'BR', escudo: 'associacao-atletica-internacional-limeira.png' },
  { id: 'associacao-atletica-sao-bento-sao-paulo', nome: "AA São Bento", pais: 'BR', escudo: 'associacao-atletica-sao-bento-sao-paulo.png' },
  { id: 'associacao-desportiva-cabofriense', nome: "Cabofriense", pais: 'BR', escudo: 'associacao-desportiva-cabofriense.svg' },
  { id: 'associacao-desportiva-sao-caetano', nome: "São Caetano", pais: 'BR', escudo: 'associacao-desportiva-sao-caetano.png' },
  { id: 'associazione-calcio-cesena', nome: "Cesena", pais: 'IT', escudo: 'associazione-calcio-cesena.png' },
  { id: 'associazione-calcio-mantova', nome: "Mantova", pais: 'IT', escudo: 'associazione-calcio-mantova.svg' },
  { id: 'associazione-calcio-reggiana-1919', nome: "Reggiana", pais: 'IT', escudo: 'associazione-calcio-reggiana-1919.png' },
  { id: 'aston-villa', nome: "Aston Villa", pais: 'EN', escudo: 'aston-villa.png' },
  { id: 'atalanta', nome: "Atalanta", pais: 'IT', escudo: 'atalanta.svg' },
  { id: 'athletic-bilbao', nome: "Athletic Bilbao", pais: 'ES', escudo: 'athletic-bilbao.png' },
  { id: 'atletico-dallas', nome: "Atlético Dallas", pais: 'US', escudo: 'atletico-dallas.png' },
  { id: 'atletico-madrid', nome: "Atlético de Madrid", pais: 'ES', escudo: 'atletico-madrid.svg' },
  { id: 'atletico-rio-negro-clube-amazonas', nome: "Rio Negro-AM", pais: 'BR', escudo: 'atletico-rio-negro-clube-amazonas.png' },
  { id: 'audax-italiano', nome: "Audax Italiano", pais: 'CL', escudo: 'audax-italiano.png' },
  { id: 'austria-vienna', nome: "Austria Vienna", pais: 'AT', escudo: 'austria-vienna.png' },
  { id: 'avai', nome: "Avaí", pais: 'BR', escudo: 'avai.svg' },
  { id: 'bahia', nome: "Bahia", pais: 'BR', escudo: 'bahia.svg' },
  { id: 'banfield', nome: "Banfield", pais: 'AR', escudo: 'banfield.svg' },
  { id: 'bangu-atletico-clube', nome: "Bangu", pais: 'BR', escudo: 'bangu-atletico-clube.svg' },
  { id: 'barcelona', nome: "Barcelona", pais: 'ES', escudo: 'barcelona.svg' },
  { id: 'barnsley-football-club', nome: "Barnsley", pais: 'EN', escudo: 'barnsley-football-club.png' },
  { id: 'basel', nome: "Basel", pais: 'CH', escudo: 'basel.png' },
  { id: 'batatais-futebol-clube', nome: "Batatais", pais: 'BR', escudo: 'batatais-futebol-clube.png' },
  { id: 'bayer-leverkusen', nome: "Bayer Leverkusen", pais: 'DE', escudo: 'bayer-leverkusen.png' },
  { id: 'bayern', nome: "Bayern de Munique", pais: 'DE', escudo: 'bayern.svg' },
  { id: 'beijing-guoan-football-club', nome: "Beijing Guoan", pais: 'CN', escudo: 'beijing-guoan-football-club.png' },
  { id: 'beitar-jerusalem', nome: "Beitar Jerusalem", pais: 'IL', escudo: 'beitar-jerusalem.png' },
  { id: 'benfica', nome: "Benfica", pais: 'PT', escudo: 'benfica.png' },
  { id: 'besiktas', nome: "Beşiktaş", pais: 'TR', escudo: 'besiktas.png' },
  { id: 'birmingham-city', nome: "Birmingham City", pais: 'EN', escudo: 'birmingham-city.png' },
  { id: 'bk-hacken', nome: "BK Häcken", pais: 'SE', escudo: 'bk-hacken.png' },
  { id: 'blackburn-rovers-football-club', nome: "Blackburn", pais: 'EN', escudo: 'blackburn-rovers-football-club.png' },
  { id: 'blackpool-football-club', nome: "Blackpool", pais: 'EN', escudo: 'blackpool-football-club.png' },
  { id: 'boca-juniors', nome: "Boca Juniors", pais: 'AR', escudo: 'boca-juniors.svg' },
  { id: 'bolton-wanderers-football-club', nome: "Bolton", pais: 'EN', escudo: 'bolton-wanderers-football-club.png' },
  { id: 'bonsucesso-futebol-clube', nome: "Bonsucesso", pais: 'BR', escudo: 'bonsucesso-futebol-clube.png' },
  { id: 'bor-m-gladbach', nome: "Bor. M'gladbach", pais: 'DE', escudo: 'bor-m-gladbach.png' },
  { id: 'bordeaux', nome: "Bordeaux", pais: 'FR', escudo: 'bordeaux.png' },
  { id: 'botafogo', nome: "Botafogo", pais: 'BR', escudo: 'botafogo.svg' },
  { id: 'botafogo-futebol-clube-ribeirao-preto', nome: "Botafogo-SP", pais: 'BR', escudo: 'botafogo-futebol-clube-ribeirao-preto.png' },
  { id: 'bournemouth', nome: "Bournemouth", pais: 'EN', escudo: 'bournemouth.svg' },
  { id: 'bradford-city-association-football-club', nome: "Bradford City", pais: 'EN', escudo: 'bradford-city-association-football-club.png' },
  { id: 'brasiliense-futebol-clube', nome: "Brasiliense", pais: 'BR', escudo: 'brasiliense-futebol-clube.png' },
  { id: 'brentford', nome: "Brentford", pais: 'EN', escudo: 'brentford.svg' },
  { id: 'brescia', nome: "Brescia", pais: 'IT', escudo: 'brescia.png' },
  { id: 'brighton', nome: "Brighton", pais: 'EN', escudo: 'brighton.svg' },
  { id: 'burnley', nome: "Burnley", pais: 'EN', escudo: 'burnley.svg' },
  { id: 'burton-albion-football-club', nome: "Burton Albion", pais: 'EN', escudo: 'burton-albion-football-club.png' },
  { id: 'cagliari', nome: "Cagliari", pais: 'IT', escudo: 'cagliari.svg' },
  { id: 'calcio-padova', nome: "Calcio Padova", pais: 'IT', escudo: 'calcio-padova.png' },
  { id: 'campinas-fc', nome: "Campinas FC", pais: 'BR', escudo: 'campinas-fc.png' },
  { id: 'cardiff-city-football-club', nome: "Cardiff", pais: 'EN', escudo: 'cardiff-city-football-club.png' },
  { id: 'carlisle-united-football-club', nome: "Carlisle United", pais: 'EN', escudo: 'carlisle-united-football-club.png' },
  { id: 'carpi-f-c-1909', nome: "Carpi F. C. 1909", pais: 'IT', escudo: 'carpi-f-c-1909.png' },
  { id: 'catania-fc', nome: "Catania FC", pais: 'IT', escudo: 'catania-fc.png' },
  { id: 'ceara', nome: "Ceará", pais: 'BR', escudo: 'ceara.svg' },
  { id: 'celtic-football-club', nome: "Celtic", pais: 'EN', escudo: 'celtic-football-club.png' },
  { id: 'cerezo-osaka', nome: "Cerezo Osaka", pais: 'JP', escudo: 'cerezo-osaka.png' },
  { id: 'cf-monterrey', nome: "CF Monterrey", pais: 'MX', escudo: 'cf-monterrey.svg' },
  { id: 'cf-montreal-q167615', nome: "CF Montréal", pais: 'CA', escudo: 'cf-montreal-q167615.svg' },
  { id: 'cf-pachuca', nome: "CF Pachuca", pais: 'MX', escudo: 'cf-pachuca.svg' },
  { id: 'chapecoense', nome: "Chapecoense", pais: 'BR', escudo: 'chapecoense.png' },
  { id: 'chelsea', nome: "Chelsea", pais: 'EN', escudo: 'chelsea.png' },
  { id: 'chennaiyin-football-club', nome: "Chennaiyin", pais: 'IN', escudo: 'chennaiyin-football-club.png' },
  { id: 'chicago-fire', nome: "Chicago Fire", pais: 'US', escudo: 'chicago-fire.svg' },
  { id: 'club-athletico-paranaense', nome: "Athletico-PR", pais: 'BR', escudo: 'club-athletico-paranaense.png' },
  { id: 'club-atletico-talleres-remedios-de-escalada', nome: "Talleres de Escalada", pais: 'AR', escudo: 'club-atletico-talleres-remedios-de-escalada.svg' },
  { id: 'club-deportivo-guadalajara', nome: "Chivas", pais: 'MX', escudo: 'club-deportivo-guadalajara.png' },
  { id: 'club-social-y-deportivo-dorados-de-sinaloa', nome: "Dorados", pais: 'MX', escudo: 'club-social-y-deportivo-dorados-de-sinaloa.png' },
  { id: 'club-universidad-nacional', nome: "Pumas", pais: 'MX', escudo: 'club-universidad-nacional.png' },
  { id: 'clube-atletico-juventus', nome: "Juventus-SP", pais: 'BR', escudo: 'clube-atletico-juventus.png' },
  { id: 'clube-atletico-mineiro', nome: "Atlético-MG", pais: 'BR', escudo: 'clube-atletico-mineiro.svg' },
  { id: 'clube-do-remo', nome: "Clube do Remo", pais: 'BR', escudo: 'clube-do-remo.png' },
  { id: 'colo-colo', nome: "Colo-Colo", pais: 'CL', escudo: 'colo-colo.png' },
  { id: 'comercial-futebol-clube-ribeirao-preto', nome: "Comercial-SP", pais: 'BR', escudo: 'comercial-futebol-clube-ribeirao-preto.png' },
  { id: 'como', nome: "Como", pais: 'IT', escudo: 'como.svg' },
  { id: 'consadole-sapporo', nome: "Consadole Sapporo", pais: 'JP', escudo: 'consadole-sapporo.png' },
  { id: 'cordoba', nome: "Córdoba", pais: 'ES', escudo: 'cordoba.svg' },
  { id: 'corinthians', nome: "Corinthians", pais: 'BR', escudo: 'corinthians.png' },
  { id: 'coritiba', nome: "Coritiba", pais: 'BR', escudo: 'coritiba.svg' },
  { id: 'coventry-city', nome: "Coventry City", pais: 'EN', escudo: 'coventry-city.png' },
  { id: 'crb', nome: "CRB", pais: 'BR', escudo: 'crb.svg' },
  { id: 'cremonese', nome: "Cremonese", pais: 'IT', escudo: 'cremonese.svg' },
  { id: 'cruzeiro', nome: "Cruzeiro", pais: 'BR', escudo: 'cruzeiro.svg' },
  { id: 'crystal-palace', nome: "Crystal Palace", pais: 'EN', escudo: 'crystal-palace.png' },
  { id: 'cska-moscow', nome: "CSKA Moscou", pais: 'RU', escudo: 'cska-moscow.png' },
  { id: 'cska-sofia', nome: "CSKA Sofia", pais: 'BG', escudo: 'cska-sofia.png' },
  { id: 'danubio', nome: "danubio", pais: 'UY', escudo: 'danubio.png' },
  { id: 'darlington-football-club-1883', nome: "Darlington", pais: 'EN', escudo: 'darlington-football-club-1883.png' },
  { id: 'dc-united', nome: "DC United", pais: 'US', escudo: 'dc-united.svg' },
  { id: 'democrata-futebol-clube', nome: "Democrata-SL", pais: 'BR', escudo: 'democrata-futebol-clube.png' },
  { id: 'deportivo-a-coruna', nome: "Deportivo A Coruña", pais: 'ES', escudo: 'deportivo-a-coruna.png' },
  { id: 'derby-county-football-club', nome: "Derby County", pais: 'EN', escudo: 'derby-county-football-club.png' },
  { id: 'emelec', nome: "emelec", pais: 'EC', escudo: 'emelec.png' },
  { id: 'emirates-club', nome: "Emirates Club", pais: 'AE', escudo: 'emirates-club.png' },
  { id: 'empoli', nome: "Empoli", pais: 'IT', escudo: 'empoli.svg' },
  { id: 'enosi-neon-ypsona-digenis-ipsona', nome: "Krasava ENY", pais: 'CY', escudo: 'enosi-neon-ypsona-digenis-ipsona.png' },
  { id: 'espanyol', nome: "Espanyol", pais: 'ES', escudo: 'espanyol.svg' },
  { id: 'esporte-clube-agua-santa', nome: "Água Santa", pais: 'BR', escudo: 'esporte-clube-agua-santa.png' },
  { id: 'esporte-clube-juventude', nome: "Juventude", pais: 'BR', escudo: 'esporte-clube-juventude.png' },
  { id: 'esporte-clube-santo-andre', nome: "Santo André", pais: 'BR', escudo: 'esporte-clube-santo-andre.png' },
  { id: 'esporte-clube-sao-bento', nome: "São Bento", pais: 'BR', escudo: 'esporte-clube-sao-bento.png' },
  { id: 'esporte-clube-sao-jose', nome: "São José-RS", pais: 'BR', escudo: 'esporte-clube-sao-jose.png' },
  { id: 'esporte-clube-xv-de-novembro-jau', nome: "XV de Jaú", pais: 'BR', escudo: 'esporte-clube-xv-de-novembro-jau.svg' },
  { id: 'estac-troyes', nome: "ESTAC Troyes", pais: 'FR', escudo: 'estac-troyes.png' },
  { id: 'estrela-vermelha-de-belgrado', nome: "Estrela Vermelha", pais: 'RS', escudo: 'estrela-vermelha-de-belgrado.svg' },
  { id: 'estudiantes', nome: "Estudiantes", pais: 'AR', escudo: 'estudiantes.svg' },
  { id: 'everton', nome: "Everton", pais: 'EN', escudo: 'everton.png' },
  { id: 'fc-anji-makhachkala', nome: "Anzhi", pais: 'RU', escudo: 'fc-anji-makhachkala.png' },
  { id: 'fc-groningen', nome: "FC Groningen", pais: 'NL', escudo: 'fc-groningen.png' },
  { id: 'fc-metz', nome: "FC Metz", pais: 'FR', escudo: 'fc-metz.svg' },
  { id: 'fc-sion', nome: "FC Sion", pais: 'CH', escudo: 'fc-sion.png' },
  { id: 'fc-tokyo', nome: "FC Tokyo", pais: 'JP', escudo: 'fc-tokyo.svg' },
  { id: 'fc-twente-enschede', nome: "Twente", pais: 'NL', escudo: 'fc-twente-enschede.png' },
  { id: 'fc-utrecht', nome: "FC Utrecht", pais: 'NL', escudo: 'fc-utrecht.png' },
  { id: 'fc-zenit-sao-petersburgo', nome: "Zenit", pais: 'RU', escudo: 'fc-zenit-sao-petersburgo.svg' },
  { id: 'fenerbahce', nome: "Fenerbahçe", pais: 'TR', escudo: 'fenerbahce.png' },
  { id: 'feyenoord', nome: "Feyenoord", pais: 'NL', escudo: 'feyenoord.png' },
  { id: 'figueirense', nome: "Figueirense", pais: 'BR', escudo: 'figueirense.svg' },
  { id: 'fiorentina', nome: "Fiorentina", pais: 'IT', escudo: 'fiorentina.svg' },
  { id: 'fk-partizan-belgrade', nome: "Partizan", pais: 'RS', escudo: 'fk-partizan-belgrade.png' },
  { id: 'fk-teleoptik', nome: "FK Teleoptik", pais: 'RS', escudo: 'fk-teleoptik.png' },
  { id: 'flamengo', nome: "Flamengo", pais: 'BR', escudo: 'flamengo.svg' },
  { id: 'fleetwood-town-football-club', nome: "Fleetwood", pais: 'EN', escudo: 'fleetwood-town-football-club.png' },
  { id: 'fluminense', nome: "Fluminense", pais: 'BR', escudo: 'fluminense.svg' },
  { id: 'football-club-halifax-town', nome: "Halifax Town", pais: 'EN', escudo: 'football-club-halifax-town.png' },
  { id: 'fortaleza-esporte-clube', nome: "Fortaleza", pais: 'BR', escudo: 'fortaleza-esporte-clube.png' },
  { id: 'fortuna-sittard', nome: "Fortuna Sittard", pais: 'NL', escudo: 'fortuna-sittard.png' },
  { id: 'fulham', nome: "Fulham", pais: 'EN', escudo: 'fulham.svg' },
  { id: 'galatasaray', nome: "Galatasaray", pais: 'TR', escudo: 'galatasaray.png' },
  { id: 'gamba-osaka', nome: "Gamba Osaka", pais: 'JP', escudo: 'gamba-osaka.svg' },
  { id: 'genoa', nome: "Genoa", pais: 'IT', escudo: 'genoa.svg' },
  { id: 'getafe', nome: "Getafe", pais: 'ES', escudo: 'getafe.png' },
  { id: 'gijon', nome: "Gijón", pais: 'ES', escudo: 'gijon.svg' },
  { id: 'gil-vicente-fc', nome: "Gil Vicente FC", pais: 'PT', escudo: 'gil-vicente-fc.png' },
  { id: 'girona', nome: "Girona", pais: 'ES', escudo: 'girona.svg' },
  { id: 'gnk-dinamo-zagreb', nome: "Dinamo Zagreb", pais: 'HR', escudo: 'gnk-dinamo-zagreb.png' },
  { id: 'goianesia-esporte-clube', nome: "Goianésia", pais: 'BR', escudo: 'goianesia-esporte-clube.png' },
  { id: 'goias', nome: "Goiás", pais: 'BR', escudo: 'goias.svg' },
  { id: 'gremio', nome: "Grêmio", pais: 'BR', escudo: 'gremio.svg' },
  { id: 'guangzhou-evergrande', nome: "Guangzhou Evergrande", pais: 'CN', escudo: 'guangzhou-evergrande.png' },
  { id: 'guarani-futebol-clube', nome: "Guarani", pais: 'BR', escudo: 'guarani-futebol-clube.svg' },
  { id: 'guaratingueta-futebol-ltda', nome: "Guaratinguetá", pais: 'BR', escudo: 'guaratingueta-futebol-ltda.png' },
  { id: 'hajduk-split', nome: "Hajduk Split", pais: 'HR', escudo: 'hajduk-split.png' },
  { id: 'halmstads-bk', nome: "Halmstads BK", pais: 'SE', escudo: 'halmstads-bk.png' },
  { id: 'hamburgo', nome: "Hamburgo", pais: 'DE', escudo: 'hamburgo.svg' },
  { id: 'hangzhou-greentown-football-club', nome: "Hangzhou Greentown", pais: 'CN', escudo: 'hangzhou-greentown-football-club.png' },
  { id: 'hannover', nome: "Hannover", pais: 'DE', escudo: 'hannover.svg' },
  { id: 'hebei-football-club', nome: "Hebei", pais: 'CN', escudo: 'hebei-football-club.png' },
  { id: 'henan-songshan-longmen-football-club', nome: "Henan", pais: 'CN', escudo: 'henan-songshan-longmen-football-club.png' },
  { id: 'hoffenheim', nome: "Hoffenheim", pais: 'DE', escudo: 'hoffenheim.svg' },
  { id: 'hotspur', nome: "Tottenham", pais: 'EN', escudo: 'hotspur.svg' },
  { id: 'huracan', nome: "Huracán", pais: 'AR', escudo: 'huracan.svg' },
  { id: 'independiente', nome: "Independiente", pais: 'AR', escudo: 'independiente.svg' },
  { id: 'instituto', nome: "Instituto", pais: 'AR', escudo: 'instituto.svg' },
  { id: 'inter', nome: "Inter de Milão", pais: 'IT', escudo: 'inter.png' },
  { id: 'inter-miami', nome: "Inter Miami", pais: 'US', escudo: 'inter-miami.svg' },
  { id: 'internacional', nome: "Internacional", pais: 'BR', escudo: 'internacional.svg' },
  { id: 'ipswich', nome: "Ipswich", pais: 'EN', escudo: 'ipswich.png' },
  { id: 'istanbul-buyuksehir-belediyespor', nome: "Başakşehir", pais: 'TR', escudo: 'istanbul-buyuksehir-belediyespor.png' },
  { id: 'itumbiara-esporte-clube', nome: "Itumbiara", pais: 'BR', escudo: 'itumbiara-esporte-clube.png' },
  { id: 'jamshedpur-fc', nome: "Jamshedpur FC", pais: 'IN', escudo: 'jamshedpur-fc.png' },
  { id: 'joinville', nome: "Joinville", pais: 'BR', escudo: 'joinville.png' },
  { id: 'jubiro-iwata', nome: "Jubiro Iwata", pais: 'JP', escudo: 'jubiro-iwata.png' },
  { id: 'juventus', nome: "Juventus", pais: 'IT', escudo: 'juventus.svg' },
  { id: 'karlsruher', nome: "Karlsruher", pais: 'DE', escudo: 'karlsruher.svg' },
  { id: 'kas-eupen', nome: "KAS Eupen", pais: 'BE', escudo: 'kas-eupen.png' },
  { id: 'kashima-antlers', nome: "Kashima Antlers", pais: 'JP', escudo: 'kashima-antlers.svg' },
  { id: 'kashiwa-reysol', nome: "Kashiwa Reysol", pais: 'JP', escudo: 'kashiwa-reysol.png' },
  { id: 'kawasaki-frontale', nome: "Kawasaki Frontale", pais: 'JP', escudo: 'kawasaki-frontale.png' },
  { id: 'kerala-blaster-football-club', nome: "Kerala Blasters", pais: 'IN', escudo: 'kerala-blaster-football-club.png' },
  { id: 'kitchee-sc', nome: "Kitchee SC", pais: 'HK', escudo: 'kitchee-sc.svg' },
  { id: 'kocaelispor', nome: "Kocaelispor", pais: 'TR', escudo: 'kocaelispor.png' },
  { id: 'konyaspor', nome: "Konyaspor", pais: 'TR', escudo: 'konyaspor.png' },
  { id: 'kuwait-sc', nome: "Kuwait SC", pais: 'KW', escudo: 'kuwait-sc.png' },
  { id: 'kyoto-sanga', nome: "Kyoto Sanga", pais: 'JP', escudo: 'kyoto-sanga.png' },
  { id: 'la-galaxy', nome: "LA Galaxy", pais: 'US', escudo: 'la-galaxy.svg' },
  { id: 'lazio', nome: "Lazio", pais: 'IT', escudo: 'lazio.svg' },
  { id: 'lecce', nome: "Lecce", pais: 'IT', escudo: 'lecce.png' },
  { id: 'leicester', nome: "Leicester", pais: 'EN', escudo: 'leicester.png' },
  { id: 'lekhwiya-sports-club', nome: "Al-Duhail", pais: 'QA', escudo: 'lekhwiya-sports-club.png' },
  { id: 'lens', nome: "Lens", pais: 'FR', escudo: 'lens.png' },
  { id: 'leyton-orient-football-club', nome: "Leyton Orient", pais: 'EN', escudo: 'leyton-orient-football-club.png' },
  { id: 'liverpool', nome: "Liverpool", pais: 'EN', escudo: 'liverpool.svg' },
  { id: 'lokomotiv-moscow', nome: "Lokomotiv Moscou", pais: 'RU', escudo: 'lokomotiv-moscow.png' },
  { id: 'londrina', nome: "Londrina", pais: 'BR', escudo: 'londrina.png' },
  { id: 'los-angeles-football-club', nome: "Los Angeles FC", pais: 'US', escudo: 'los-angeles-football-club.svg' },
  { id: 'machida-zelvia', nome: "Machida Zelvia", pais: 'JP', escudo: 'machida-zelvia.svg' },
  { id: 'mallorca', nome: "Mallorca", pais: 'ES', escudo: 'mallorca.png' },
  { id: 'man-city', nome: "Man City", pais: 'EN', escudo: 'man-city.png' },
  { id: 'manchester-city', nome: "Manchester City", pais: 'EN', escudo: 'manchester-city.png' },
  { id: 'manchester-united', nome: "Manchester United", pais: 'EN', escudo: 'manchester-united.png' },
  { id: 'manchete-futebol-clube-do-recife', nome: "Manchete", pais: 'BR', escudo: 'manchete-futebol-clube-do-recife.png' },
  { id: 'marseille', nome: "Marselha", pais: 'FR', escudo: 'marseille.svg' },
  { id: 'melbourne-city-football-club', nome: "Melbourne City", pais: 'AU', escudo: 'melbourne-city-football-club.png' },
  { id: 'miami-fc-2006', nome: "Miami FC", pais: 'US', cores: ['#0A3D91', '#FFFFFF'] },
  { id: 'miami-united', nome: "Miami United", pais: 'US', escudo: 'miami-united.png' },
  { id: 'milan', nome: "Milan", pais: 'IT', escudo: 'milan.svg' },
  { id: 'millonarios', nome: "millonarios", pais: 'CO', escudo: 'millonarios.png' },
  { id: 'millwall-football-club', nome: "Millwall", pais: 'EN', escudo: 'millwall-football-club.png' },
  { id: 'milton-keynes-dons-football-club', nome: "MK Dons", pais: 'EN', escudo: 'milton-keynes-dons-football-club.png' },
  { id: 'mogi-mirim', nome: "Mogi Mirim", pais: 'BR', escudo: 'mogi-mirim.svg' },
  { id: 'monaco', nome: "Monaco", pais: 'FR', escudo: 'monaco.svg' },
  { id: 'monza', nome: "Monza", pais: 'IT', escudo: 'monza.svg' },
  { id: 'mumbai-city-football-club', nome: "Mumbai City", pais: 'IN', escudo: 'mumbai-city-football-club.png' },
  { id: 'murici-futebol-clube', nome: "Murici", pais: 'BR', escudo: 'murici-futebol-clube.png' },
  { id: 'nacional', nome: "nacional", pais: 'UY', escudo: 'nacional.png' },
  { id: 'nagoya-grampus', nome: "Nagoya Grampus", pais: 'JP', escudo: 'nagoya-grampus.svg' },
  { id: 'nantes', nome: "Nantes", pais: 'FR', escudo: 'nantes.svg' },
  { id: 'napoli', nome: "Napoli", pais: 'IT', escudo: 'napoli.svg' },
  { id: 'nautico', nome: "Nautico", pais: 'BR', escudo: 'nautico.svg' },
  { id: 'new-york-cosmos', nome: "New York Cosmos", pais: 'US', escudo: 'new-york-cosmos.png' },
  { id: 'newcastle', nome: "Newcastle", pais: 'EN', escudo: 'newcastle.png' },
  { id: 'newell-s', nome: "Newell's", pais: 'AR', escudo: 'newell-s.svg' },
  { id: 'nice', nome: "Nice", pais: 'FR', escudo: 'nice.png' },
  { id: 'nk-inter-zapresic', nome: "Inter Zaprešić", pais: 'HR', escudo: 'nk-inter-zapresic.png' },
  { id: 'norwich', nome: "Norwich", pais: 'EN', escudo: 'norwich.png' },
  { id: 'nottingham', nome: "Nottingham", pais: 'EN', escudo: 'nottingham.svg' },
  { id: 'nova-iguacu-futebol-clube', nome: "Nova Iguaçu", pais: 'BR', escudo: 'nova-iguacu-futebol-clube.png' },
  { id: 'odisha-fc', nome: "Odisha FC", pais: 'IN', escudo: 'odisha-fc.png' },
  { id: 'oita-trinita', nome: "Oita Trinita", pais: 'JP', escudo: 'oita-trinita.svg' },
  { id: 'olaria-atletico-clube', nome: "Olaria", pais: 'BR', escudo: 'olaria-atletico-clube.png' },
  { id: 'olympiacos-piraeus', nome: "Olympiacos", pais: 'GR', escudo: 'olympiacos-piraeus.png' },
  { id: 'olympique-lyon', nome: "Olympique Lyon", pais: 'FR', escudo: 'olympique-lyon.png' },
  { id: 'omiya-ardija', nome: "Omiya Ardija", pais: 'JP', escudo: 'omiya-ardija.svg' },
  { id: 'operario-ferroviario-esporte-clube', nome: "Operário-PR", pais: 'BR', escudo: 'operario-ferroviario-esporte-clube.png' },
  { id: 'orlando-city', nome: "Orlando City", pais: 'US', escudo: 'orlando-city.svg' },
  { id: 'os-belenenses', nome: "Belenenses", pais: 'PT', escudo: 'os-belenenses.png' },
  { id: 'osasuna', nome: "Osasuna", pais: 'ES', escudo: 'osasuna.svg' },
  { id: 'oxford-united-football-club', nome: "Oxford United", pais: 'EN', escudo: 'oxford-united-football-club.png' },
  { id: 'pafos-fc', nome: "Pafos FC", pais: 'CY', escudo: 'pafos-fc.png' },
  { id: 'palermo-football-club', nome: "Palermo", pais: 'IT', escudo: 'palermo-football-club.png' },
  { id: 'palmeiras', nome: "Palmeiras", pais: 'BR', escudo: 'palmeiras.svg' },
  { id: 'panathinaikos', nome: "Panathinaikos", pais: 'GR', escudo: 'panathinaikos.png' },
  { id: 'panionios', nome: "Panionios", pais: 'GR', escudo: 'panionios.png' },
  { id: 'paok-thessaloniki', nome: "PAOK", pais: 'GR', escudo: 'paok-thessaloniki.png' },
  { id: 'parma', nome: "Parma", pais: 'IT', escudo: 'parma.svg' },
  { id: 'penarol', nome: "penarol", pais: 'UY', escudo: 'penarol.png' },
  { id: 'perugia-calcio', nome: "Perugia Calcio", pais: 'IT', escudo: 'perugia-calcio.png' },
  { id: 'pescara-calcio', nome: "Pescara Calcio", pais: 'IT', escudo: 'pescara-calcio.png' },
  { id: 'pisa', nome: "Pisa", pais: 'IT', escudo: 'pisa.svg' },
  { id: 'ponte-preta', nome: "Ponte Preta", pais: 'BR', escudo: 'ponte-preta.svg' },
  { id: 'porto', nome: "Porto", pais: 'PT', escudo: 'porto.png' },
  { id: 'portuguesa', nome: "Portuguesa", pais: 'BR', escudo: 'portuguesa.png' },
  { id: 'preston-north-end-football-club', nome: "Preston", pais: 'EN', escudo: 'preston-north-end-football-club.png' },
  { id: 'psg', nome: "PSG", pais: 'FR', escudo: 'psg.png' },
  { id: 'psv', nome: "PSV", pais: 'NL', escudo: 'psv.png' },
  { id: 'qatar-sports-club', nome: "Qatar SC", pais: 'QA', escudo: 'qatar-sports-club.png' },
  { id: 'queretaro', nome: "queretaro", pais: 'MX', escudo: 'queretaro.png' },
  { id: 'quick-boys', nome: "Quick Boys", pais: 'NL', escudo: 'quick-boys.png' },
  { id: 'rangers-football-club', nome: "Rangers", pais: 'EN', escudo: 'rangers-football-club.png' },
  { id: 'reading', nome: "Reading", pais: 'EN', escudo: 'reading.png' },
  { id: 'real-betis', nome: "Real Betis", pais: 'ES', escudo: 'real-betis.svg' },
  { id: 'real-madrid', nome: "Real Madrid", pais: 'ES', escudo: 'real-madrid.png' },
  { id: 'red-bull-new-york', nome: "Red Bull New York", pais: 'US', escudo: 'red-bull-new-york.svg' },
  { id: 'river-plate', nome: "River Plate", pais: 'AR', escudo: 'river-plate.svg' },
  { id: 'rkc-waalwijk', nome: "RKC Waalwijk", pais: 'NL', escudo: 'rkc-waalwijk.png' },
  { id: 'roma', nome: "Roma", pais: 'IT', escudo: 'roma.png' },
  { id: 'rosario-central', nome: "Rosario Central", pais: 'AR', escudo: 'rosario-central.svg' },
  { id: 'rotherham-united-football-club', nome: "Rotherham", pais: 'EN', escudo: 'rotherham-united-football-club.png' },
  { id: 'rsc-anderlecht', nome: "RSC Anderlecht", pais: 'BE', escudo: 'rsc-anderlecht.png' },
  { id: 'saint-etienne', nome: "Saint-Étienne", pais: 'FR', escudo: 'saint-etienne.svg' },
  { id: 'samsunspor', nome: "Samsunspor", pais: 'TR', escudo: 'samsunspor.png' },
  { id: 'sanfrecce-hiroshima', nome: "Sanfrecce Hiroshima", pais: 'JP', escudo: 'sanfrecce-hiroshima.png' },
  { id: 'santa-cruz', nome: "Santa Cruz", pais: 'BR', escudo: 'santa-cruz.svg' },
  { id: 'santos', nome: "Santos", pais: 'BR', escudo: 'santos.svg' },
  { id: 'sao-bernardo-futebol-clube', nome: "São Bernardo", pais: 'BR', escudo: 'sao-bernardo-futebol-clube.png' },
  { id: 'sao-jose-esporte-clube', nome: "São José-SP", pais: 'BR', escudo: 'sao-jose-esporte-clube.png' },
  { id: 'sao-paulo', nome: "São Paulo", pais: 'BR', escudo: 'sao-paulo.svg' },
  { id: 'sassuolo', nome: "Sassuolo", pais: 'IT', escudo: 'sassuolo.svg' },
  { id: 'sc-braga', nome: "SC Braga", pais: 'PT', escudo: 'sc-braga.png' },
  { id: 'sc-telstar', nome: "SC Telstar", pais: 'NL', escudo: 'sc-telstar.png' },
  { id: 'schalke', nome: "Schalke 04", pais: 'DE', escudo: 'schalke.svg' },
  { id: 'seattle-sounders', nome: "Seattle Sounders", pais: 'US', escudo: 'seattle-sounders.svg' },
  { id: 'servette-fc', nome: "Servette FC", pais: 'CH', escudo: 'servette-fc.png' },
  { id: 'sevilla', nome: "Sevilla", pais: 'ES', escudo: 'sevilla.png' },
  { id: 'shakhtar', nome: "Shakhtar Donetsk", pais: 'UA', escudo: 'shakhtar.png' },
  { id: 'shandong-luneng', nome: "Shandong Taishan", pais: 'CN', escudo: 'shandong-luneng.png' },
  { id: 'shanghai-shenhua', nome: "Shanghai Shenhua", pais: 'CN', escudo: 'shanghai-shenhua.png' },
  { id: 'shanghai-sipg', nome: "Shanghai Port", pais: 'CN', escudo: 'shanghai-sipg.png' },
  { id: 'sharjah-fc', nome: "Sharjah FC", pais: 'AE', escudo: 'sharjah-fc.png' },
  { id: 'sheffield-wednesday', nome: "Sheffield Wednesday", pais: 'EN', escudo: 'sheffield-wednesday.png' },
  { id: 'shimizu-s-pulse', nome: "Shimizu S-Pulse", pais: 'JP', escudo: 'shimizu-s-pulse.svg' },
  { id: 'shonan-bellmare', nome: "Shonan Bellmare", pais: 'JP', escudo: 'shonan-bellmare.svg' },
  { id: 'shrewsbury-town-football-club', nome: "Shrewsbury", pais: 'EN', escudo: 'shrewsbury-town-football-club.png' },
  { id: 'sinop-futebol-clube', nome: "Sinop", pais: 'BR', escudo: 'sinop-futebol-clube.png' },
  { id: 'siracusa-calcio-1924', nome: "Siracusa", pais: 'IT', escudo: 'siracusa-calcio-1924.png' },
  { id: 'sivasspor', nome: "Sivasspor", pais: 'TR', escudo: 'sivasspor.png' },
  { id: 'sobradinho-esporte-clube', nome: "Sobradinho", pais: 'BR', escudo: 'sobradinho-esporte-clube.png' },
  { id: 'southampton', nome: "Southampton", pais: 'EN', escudo: 'southampton.png' },
  { id: 'spartak', nome: "Spartak", pais: 'RS', escudo: 'spartak.png' },
  { id: 'spartak-moscow', nome: "Spartak Moscow", pais: 'RU', escudo: 'spartak-moscow.png' },
  { id: 'sport', nome: "Sport Recife", pais: 'BR', escudo: 'sport.png' },
  { id: 'sporting-cp', nome: "Sporting", pais: 'PT', escudo: 'sporting-cp.png' },
  { id: 'standard-liege', nome: "Standard Liège", pais: 'BE', escudo: 'standard-liege.png' },
  { id: 'stocksbridge-park-steels-f-c', nome: "Stocksbridge", pais: 'EN', escudo: 'stocksbridge-park-steels-f-c.png' },
  { id: 'stoke-city-football-club', nome: "Stoke City", pais: 'EN', escudo: 'stoke-city-football-club.png' },
  { id: 'stuttgart', nome: "Stuttgart", pais: 'DE', escudo: 'stuttgart.svg' },
  { id: 'sunderland', nome: "Sunderland", pais: 'EN', escudo: 'sunderland.svg' },
  { id: 'swindon-town-football-club', nome: "Swindon Town", pais: 'EN', escudo: 'swindon-town-football-club.png' },
  { id: 'sydney-football-club', nome: "Sydney FC", pais: 'AU', escudo: 'sydney-football-club.png' },
  { id: 'sydney-united-58-football-club', nome: "Sydney United", pais: 'AU', escudo: 'sydney-united-58-football-club.png' },
  { id: 'tianjin-tianhai-football-club', nome: "Tianjin Tianhai", pais: 'CN', escudo: 'tianjin-tianhai-football-club.png' },
  { id: 'tigres', nome: "tigres", pais: 'MX', escudo: 'tigres.png' },
  { id: 'tokyo-verdy', nome: "Tokyo Verdy", pais: 'JP', escudo: 'tokyo-verdy.svg' },
  { id: 'toluca', nome: "toluca", pais: 'MX', escudo: 'toluca.png' },
  { id: 'torino', nome: "Torino", pais: 'IT', escudo: 'torino.svg' },
  { id: 'toulouse', nome: "Toulouse", pais: 'FR', escudo: 'toulouse.png' },
  { id: 'trabzonspor', nome: "Trabzonspor", pais: 'TR', escudo: 'trabzonspor.png' },
  { id: 'tranmere-rovers-football-club', nome: "Tranmere", pais: 'EN', escudo: 'tranmere-rovers-football-club.png' },
  { id: 'tupi', nome: "Tupi", pais: 'BR', escudo: 'tupi.svg' },
  { id: 'tupynambas-futebol-clube', nome: "Tupynambás", pais: 'BR', escudo: 'tupynambas-futebol-clube.png' },
  { id: 'u-s-livorno-1915', nome: "Livorno", pais: 'IT', escudo: 'u-s-livorno-1915.png' },
  { id: 'uberlandia-esporte-clube', nome: "Uberlândia", pais: 'BR', escudo: 'uberlandia-esporte-clube.png' },
  { id: 'udinese', nome: "Udinese", pais: 'IT', escudo: 'udinese.png' },
  { id: 'uniao-sao-joao-esporte-clube', nome: "União São João", pais: 'BR', escudo: 'uniao-sao-joao-esporte-clube.png' },
  { id: 'unione-sportiva-catanzaro', nome: "Catanzaro", pais: 'IT', escudo: 'unione-sportiva-catanzaro.png' },
  { id: 'us-salernitana-1919', nome: "Salernitana", pais: 'IT', escudo: 'us-salernitana-1919.png' },
  { id: 'valencia', nome: "Valencia", pais: 'ES', escudo: 'valencia.svg' },
  { id: 'vallecano', nome: "Vallecano", pais: 'ES', escudo: 'vallecano.png' },
  { id: 'vasco', nome: "Vasco da Gama", pais: 'BR', escudo: 'vasco.svg' },
  { id: 'velez-sarsfield', nome: "Vélez Sarsfield", pais: 'AR', escudo: 'velez-sarsfield.svg' },
  { id: 'venezia', nome: "Venezia", pais: 'IT', escudo: 'venezia.svg' },
  { id: 'vestel-manisaspor', nome: "Manisaspor", pais: 'TR', escudo: 'vestel-manisaspor.png' },
  { id: 'villarreal', nome: "Villarreal", pais: 'ES', escudo: 'villarreal.svg' },
  { id: 'vissel-kobe', nome: "Vissel Kobe", pais: 'JP', escudo: 'vissel-kobe.svg' },
  { id: 'vitoria', nome: "Vitória", pais: 'BR', escudo: 'vitoria.svg' },
  { id: 'watford-fc', nome: "Watford FC", pais: 'EN', escudo: 'watford-fc.png' },
  { id: 'werder-bremen', nome: "Werder Bremen", pais: 'DE', escudo: 'werder-bremen.png' },
  { id: 'west-ham', nome: "West Ham", pais: 'EN', escudo: 'west-ham.svg' },
  { id: 'western-sydney-wanderers-football-club', nome: "Western Sydney", pais: 'AU', escudo: 'western-sydney-wanderers-football-club.png' },
  { id: 'willem-ii', nome: "Willem II", pais: 'NL', escudo: 'willem-ii.png' },
  { id: 'wisla-krakow', nome: "Wisla Kraków", pais: 'PL', escudo: 'wisla-krakow.png' },
  { id: 'wolfsburg', nome: "Wolfsburg", pais: 'DE', escudo: 'wolfsburg.svg' },
  { id: 'wolverhampton-wanderers', nome: "Wolverhampton", pais: 'EN', escudo: 'wolverhampton-wanderers.png' },
  { id: 'wuhan-three-towns-football-club', nome: "Wuhan Three Towns", pais: 'CN', escudo: 'wuhan-three-towns-football-club.png' },
  { id: 'yokohama-flugels', nome: "Yokohama Flügels", pais: 'JP', escudo: 'yokohama-flugels.png' },
  { id: 'yokohama-marinos', nome: "Yokohama Marinos", pais: 'JP', escudo: 'yokohama-marinos.png' },
  { id: 'zaragoza', nome: "Zaragoza", pais: 'ES', escudo: 'zaragoza.png' },
]

export const CLUBE_POR_ID = new Map(CLUBES.map((c) => [c.id, c]))
