// GERADO POR scripts/construir-catalogo.mjs — não edite à mão.
// Só os clubes em uso pelos jogadores; o catálogo completo, para consultar
// ao escrever uma carreira nova, está em scripts/catalogo-completo.json.
// Nome e id dos clubes usados pelos jogadores vivem em scripts/clubes-canonicos.mjs.
import type { Clube } from './tipos'

export const CLUBES: Clube[] = [
  { id: 'aarhus-gf', nome: "Aarhus GF", pais: 'DK', escudo: 'aarhus-gf.png' },
  { id: 'abc', nome: "Abc", pais: 'BR', escudo: 'abc.svg' },
  { id: 'acr-siena-1904', nome: "ACR Siena 1904", pais: 'IT', escudo: 'acr-siena-1904.png' },
  { id: 'adana-demirspor', nome: "Adana Demirspor", pais: 'TR', escudo: 'adana-demirspor.png' },
  { id: 'ajax', nome: "Ajax", pais: 'NL', escudo: 'ajax.png' },
  { id: 'al-ahli-saudi', nome: "Al-Ahli", pais: 'SA', escudo: 'al-ahli-saudi.png' },
  { id: 'al-ahli-sports-club', nome: "Al-Ahli Sports Club", pais: 'QA', escudo: 'al-ahli-sports-club.png' },
  { id: 'al-ain', nome: "Al Ain", pais: 'AE', escudo: 'al-ain.png' },
  { id: 'al-arabi-sports-club', nome: "Al-Arabi Sports Club", pais: 'QA', escudo: 'al-arabi-sports-club.png' },
  { id: 'al-ettifaq', nome: "Al-Ettifaq", pais: 'SA', escudo: 'al-ettifaq.svg' },
  { id: 'al-gharafa', nome: "Al-Gharafa", pais: 'QA', escudo: 'al-gharafa.png' },
  { id: 'al-hilal', nome: "Al-Hilal", pais: 'SA', escudo: 'al-hilal.svg' },
  { id: 'al-ittihad', nome: "Al-Ittihad", pais: 'SA', escudo: 'al-ittihad.svg' },
  { id: 'al-jaish-qatar', nome: "Al-Jaish (Qatar)", pais: 'QA', escudo: 'al-jaish-qatar.png' },
  { id: 'al-jazira', nome: "Al-Jazira", pais: 'AE', escudo: 'al-jazira.png' },
  { id: 'al-kholood', nome: "Al-Kholood", pais: 'SA', escudo: 'al-kholood.svg' },
  { id: 'al-khor-sports-club', nome: "Al-Khor Sports Club", pais: 'QA', escudo: 'al-khor-sports-club.png' },
  { id: 'al-nasr-sports-club', nome: "Al-Nasr Sports Club", pais: 'AE', escudo: 'al-nasr-sports-club.png' },
  { id: 'al-nassr', nome: "Al-Nassr", pais: 'SA', escudo: 'al-nassr.svg' },
  { id: 'al-qadsiah', nome: "Al-Qadsiah", pais: 'SA', escudo: 'al-qadsiah.svg' },
  { id: 'al-rayyan-sports-club', nome: "Al-Rayyan Sports Club", pais: 'QA', escudo: 'al-rayyan-sports-club.png' },
  { id: 'al-sadd-sports-club', nome: "Al-Sadd Sports Club", pais: 'QA', escudo: 'al-sadd-sports-club.png' },
  { id: 'al-shabab', nome: "Al-Shabab", pais: 'SA', escudo: 'al-shabab.svg' },
  { id: 'al-wahda-sports-cultural-club', nome: "Al-Wahda Sports Cultural Club", pais: 'AE', escudo: 'al-wahda-sports-cultural-club.png' },
  { id: 'al-wakrah-sports-club', nome: "Al-Wakrah Sports Club", pais: 'QA', escudo: 'al-wakrah-sports-club.png' },
  { id: 'alanyaspor', nome: "Alanyaspor", pais: 'TR', escudo: 'alanyaspor.png' },
  { id: 'albacete', nome: "Albacete", pais: 'ES', escudo: 'albacete.svg' },
  { id: 'albirex-niigata', nome: "Albirex Niigata", pais: 'JP', escudo: 'albirex-niigata.svg' },
  { id: 'america', nome: "america", pais: 'MX', escudo: 'america.png' },
  { id: 'america-football-club-rio-de-janeiro', nome: "America Football Club (Rio de Janeiro)", pais: 'BR', escudo: 'america-football-club-rio-de-janeiro.svg' },
  { id: 'america-futebol-clube-belo-horizonte', nome: "América Futebol Clube (Belo Horizonte)", pais: 'BR', escudo: 'america-futebol-clube-belo-horizonte.png' },
  { id: 'america-futebol-clube-rio-grande-do-norte', nome: "América Futebol Clube (Rio Grande do Norte)", pais: 'BR', escudo: 'america-futebol-clube-rio-grande-do-norte.svg' },
  { id: 'anapolis-futebol-clube', nome: "Anápolis Futebol Clube", pais: 'BR', escudo: 'anapolis-futebol-clube.png' },
  { id: 'antalyaspor', nome: "Antalyaspor", pais: 'TR', escudo: 'antalyaspor.png' },
  { id: 'army-united-football-club', nome: "Army United Football Club", pais: 'TH', escudo: 'army-united-football-club.png' },
  { id: 'arsenal', nome: "Arsenal", pais: 'EN', escudo: 'arsenal.svg' },
  { id: 'associacao-atletica-internacional-limeira', nome: "Associação Atlética Internacional (Limeira)", pais: 'BR', escudo: 'associacao-atletica-internacional-limeira.png' },
  { id: 'associacao-atletica-sao-bento-sao-paulo', nome: "Associação Atlética São Bento (São Paulo)", pais: 'BR', escudo: 'associacao-atletica-sao-bento-sao-paulo.png' },
  { id: 'associacao-desportiva-cabofriense', nome: "Associação Desportiva Cabofriense", pais: 'BR', escudo: 'associacao-desportiva-cabofriense.svg' },
  { id: 'associacao-desportiva-sao-caetano', nome: "Associação Desportiva São Caetano", pais: 'BR', escudo: 'associacao-desportiva-sao-caetano.png' },
  { id: 'associazione-calcio-cesena', nome: "Associazione Calcio Cesena", pais: 'IT', escudo: 'associazione-calcio-cesena.png' },
  { id: 'associazione-calcio-mantova', nome: "Associazione Calcio Mantova", pais: 'IT', escudo: 'associazione-calcio-mantova.svg' },
  { id: 'associazione-calcio-reggiana-1919', nome: "Associazione Calcio Reggiana 1919", pais: 'IT', escudo: 'associazione-calcio-reggiana-1919.png' },
  { id: 'aston-villa', nome: "Aston Villa", pais: 'EN', escudo: 'aston-villa.png' },
  { id: 'atalanta', nome: "Atalanta", pais: 'IT', escudo: 'atalanta.svg' },
  { id: 'atletico-madrid', nome: "Atlético de Madrid", pais: 'ES', escudo: 'atletico-madrid.svg' },
  { id: 'atletico-rio-negro-clube-amazonas', nome: "Atlético Rio Negro Clube (Amazonas)", pais: 'BR', escudo: 'atletico-rio-negro-clube-amazonas.png' },
  { id: 'audax-italiano', nome: "Audax Italiano", pais: 'CL', escudo: 'audax-italiano.png' },
  { id: 'augsburg', nome: "Augsburg", pais: 'DE', escudo: 'augsburg.svg' },
  { id: 'austria-vienna', nome: "Austria Vienna", pais: 'AT', escudo: 'austria-vienna.png' },
  { id: 'avai', nome: "Avai", pais: 'BR', escudo: 'avai.svg' },
  { id: 'bahia', nome: "Bahia", pais: 'BR', escudo: 'bahia.svg' },
  { id: 'bangkok-f-c', nome: "Bangkok F.C.", pais: 'TH', escudo: 'bangkok-f-c.png' },
  { id: 'bangu-atletico-clube', nome: "Bangu Atlético Clube", pais: 'BR', escudo: 'bangu-atletico-clube.svg' },
  { id: 'barcelona', nome: "Barcelona", pais: 'ES', escudo: 'barcelona.svg' },
  { id: 'basel', nome: "Basel", pais: 'CH', escudo: 'basel.png' },
  { id: 'batatais-futebol-clube', nome: "Batatais Futebol Clube", pais: 'BR', escudo: 'batatais-futebol-clube.png' },
  { id: 'bayer-leverkusen', nome: "Bayer Leverkusen", pais: 'DE', escudo: 'bayer-leverkusen.png' },
  { id: 'bayern', nome: "Bayern de Munique", pais: 'DE', escudo: 'bayern.svg' },
  { id: 'beijing-guoan-football-club', nome: "Beijing Guoan Football Club", pais: 'CN', escudo: 'beijing-guoan-football-club.png' },
  { id: 'beitar-jerusalem', nome: "Beitar Jerusalem", pais: 'IL', escudo: 'beitar-jerusalem.png' },
  { id: 'belenenses-sad', nome: "Belenenses SAD", pais: 'PT', escudo: 'belenenses-sad.png' },
  { id: 'benfica', nome: "Benfica", pais: 'PT', escudo: 'benfica.png' },
  { id: 'besiktas', nome: "Beşiktaş", pais: 'TR', escudo: 'besiktas.png' },
  { id: 'birmingham-city', nome: "Birmingham City", pais: 'EN', escudo: 'birmingham-city.png' },
  { id: 'bk-hacken', nome: "BK Häcken", pais: 'SE', escudo: 'bk-hacken.png' },
  { id: 'blackburn-rovers-football-club', nome: "Blackburn Rovers Football Club", pais: 'EN', escudo: 'blackburn-rovers-football-club.png' },
  { id: 'boca-juniors', nome: "Boca Juniors", pais: 'AR', escudo: 'boca-juniors.svg' },
  { id: 'bolton-wanderers-football-club', nome: "Bolton Wanderers Football Club", pais: 'EN', escudo: 'bolton-wanderers-football-club.png' },
  { id: 'bonsucesso-futebol-clube', nome: "Bonsucesso Futebol Clube", pais: 'BR', escudo: 'bonsucesso-futebol-clube.png' },
  { id: 'bor-m-gladbach', nome: "Bor. M'gladbach", pais: 'DE', escudo: 'bor-m-gladbach.png' },
  { id: 'bordeaux', nome: "Bordeaux", pais: 'FR', escudo: 'bordeaux.png' },
  { id: 'botafogo', nome: "Botafogo", pais: 'BR', escudo: 'botafogo.svg' },
  { id: 'botafogo-futebol-clube-ribeirao-preto', nome: "Botafogo Futebol Clube (Ribeirão Preto)", pais: 'BR', escudo: 'botafogo-futebol-clube-ribeirao-preto.png' },
  { id: 'bournemouth', nome: "Bournemouth", pais: 'EN', escudo: 'bournemouth.svg' },
  { id: 'brasil-de-pelotas', nome: "Brasil De Pelotas", pais: 'BR', escudo: 'brasil-de-pelotas.svg' },
  { id: 'brasiliense-futebol-clube', nome: "Brasiliense Futebol Clube", pais: 'BR', escudo: 'brasiliense-futebol-clube.png' },
  { id: 'brentford', nome: "Brentford", pais: 'EN', escudo: 'brentford.svg' },
  { id: 'brescia', nome: "Brescia", pais: 'IT', escudo: 'brescia.png' },
  { id: 'brighton', nome: "Brighton", pais: 'EN', escudo: 'brighton.svg' },
  { id: 'burnley', nome: "Burnley", pais: 'EN', escudo: 'burnley.svg' },
  { id: 'cagliari', nome: "Cagliari", pais: 'IT', escudo: 'cagliari.svg' },
  { id: 'calcio-padova', nome: "Calcio Padova", pais: 'IT', escudo: 'calcio-padova.png' },
  { id: 'campinas-esporte-clube-mato-grosso', nome: "Campinas Esporte Clube (Mato Grosso)", pais: 'BR', escudo: 'campinas-esporte-clube-mato-grosso.png' },
  { id: 'cardiff-city-football-club', nome: "Cardiff City Football Club", pais: 'EN', escudo: 'cardiff-city-football-club.png' },
  { id: 'carlisle-united-football-club', nome: "Carlisle United Football Club", pais: 'EN', escudo: 'carlisle-united-football-club.png' },
  { id: 'carpi-f-c-1909', nome: "Carpi F. C. 1909", pais: 'IT', escudo: 'carpi-f-c-1909.png' },
  { id: 'catania-fc', nome: "Catania FC", pais: 'IT', escudo: 'catania-fc.png' },
  { id: 'ceara', nome: "Ceara", pais: 'BR', escudo: 'ceara.svg' },
  { id: 'celtic-football-club', nome: "Celtic Football Club", pais: 'EN', escudo: 'celtic-football-club.png' },
  { id: 'central-cordoba', nome: "Central Córdoba", pais: 'AR', escudo: 'central-cordoba.svg' },
  { id: 'cerezo-osaka', nome: "Cerezo Osaka", pais: 'JP', escudo: 'cerezo-osaka.png' },
  { id: 'cf-monterrey', nome: "CF Monterrey", pais: 'MX', escudo: 'cf-monterrey.svg' },
  { id: 'cf-montreal-q167615', nome: "CF Montréal", pais: 'CA', escudo: 'cf-montreal-q167615.svg' },
  { id: 'chapecoense', nome: "Chapecoense", pais: 'BR', escudo: 'chapecoense.png' },
  { id: 'chelsea', nome: "Chelsea", pais: 'EN', escudo: 'chelsea.png' },
  { id: 'chennaiyin-football-club', nome: "Chennaiyin Football Club", pais: 'IN', escudo: 'chennaiyin-football-club.png' },
  { id: 'chicago-fire', nome: "Chicago Fire", pais: 'US', escudo: 'chicago-fire.svg' },
  { id: 'club-athletico-paranaense', nome: "Club Athletico Paranaense", pais: 'BR', escudo: 'club-athletico-paranaense.png' },
  { id: 'club-atletico-rentistas', nome: "Club Atlético Rentistas", pais: 'UY', escudo: 'club-atletico-rentistas.png' },
  { id: 'club-deportivo-atalaya', nome: "Club Deportivo Atalaya", pais: 'AR', escudo: 'club-deportivo-atalaya.png' },
  { id: 'club-deportivo-guadalajara', nome: "Club Deportivo Guadalajara", pais: 'MX', escudo: 'club-deportivo-guadalajara.png' },
  { id: 'club-social-y-deportivo-dorados-de-sinaloa', nome: "Club Social y Deportivo Dorados de Sinaloa", pais: 'MX', escudo: 'club-social-y-deportivo-dorados-de-sinaloa.png' },
  { id: 'club-universidad-nacional', nome: "Club Universidad Nacional", pais: 'MX', escudo: 'club-universidad-nacional.png' },
  { id: 'clube-atletico-juventus', nome: "Clube Atlético Juventus", pais: 'BR', escudo: 'clube-atletico-juventus.png' },
  { id: 'clube-atletico-mineiro', nome: "Clube Atlético Mineiro", pais: 'BR', escudo: 'clube-atletico-mineiro.svg' },
  { id: 'clube-atletico-taboao-da-serra', nome: "Clube Atlético Taboão da Serra", pais: 'BR', escudo: 'clube-atletico-taboao-da-serra.png' },
  { id: 'clube-do-remo', nome: "Clube do Remo", pais: 'BR', escudo: 'clube-do-remo.png' },
  { id: 'colo-colo', nome: "Colo-Colo", pais: 'CL', escudo: 'colo-colo.png' },
  { id: 'comercial-futebol-clube-ribeirao-preto', nome: "Comercial Futebol Clube (Ribeirão Preto)", pais: 'BR', escudo: 'comercial-futebol-clube-ribeirao-preto.png' },
  { id: 'como', nome: "Como", pais: 'IT', escudo: 'como.svg' },
  { id: 'consadole-sapporo', nome: "Consadole Sapporo", pais: 'JP', escudo: 'consadole-sapporo.png' },
  { id: 'cordoba', nome: "Córdoba", pais: 'ES', escudo: 'cordoba.svg' },
  { id: 'corinthians', nome: "Corinthians", pais: 'BR', escudo: 'corinthians.png' },
  { id: 'coritiba', nome: "Coritiba", pais: 'BR', escudo: 'coritiba.svg' },
  { id: 'coventry-city', nome: "Coventry City", pais: 'EN', escudo: 'coventry-city.png' },
  { id: 'cremonese', nome: "Cremonese", pais: 'IT', escudo: 'cremonese.svg' },
  { id: 'cruzeiro', nome: "Cruzeiro", pais: 'BR', escudo: 'cruzeiro.svg' },
  { id: 'crystal-palace', nome: "Crystal Palace", pais: 'EN', escudo: 'crystal-palace.png' },
  { id: 'cska-moscow', nome: "CSKA Moscou", pais: 'RU', escudo: 'cska-moscow.png' },
  { id: 'cska-sofia', nome: "CSKA Sofia", pais: 'BG', escudo: 'cska-sofia.png' },
  { id: 'd-c-united', nome: "D.C. United", pais: 'US', escudo: 'd-c-united.svg' },
  { id: 'danubio', nome: "danubio", pais: 'UY', escudo: 'danubio.png' },
  { id: 'democrata-futebol-clube', nome: "Democrata Futebol Clube", pais: 'BR', escudo: 'democrata-futebol-clube.png' },
  { id: 'deportivo-a-coruna', nome: "Deportivo A Coruña", pais: 'ES', escudo: 'deportivo-a-coruna.png' },
  { id: 'deportivo-maldonado-de-puerto-maldonado', nome: "Deportivo Maldonado de Puerto Maldonado", pais: 'PE', escudo: 'deportivo-maldonado-de-puerto-maldonado.png' },
  { id: 'derby-county-football-club', nome: "Derby County Football Club", pais: 'EN', escudo: 'derby-county-football-club.png' },
  { id: 'dusseldorf', nome: "Düsseldorf", pais: 'DE', escudo: 'dusseldorf.svg' },
  { id: 'emirates-club', nome: "Emirates Club", pais: 'AE', escudo: 'emirates-club.png' },
  { id: 'empoli', nome: "Empoli", pais: 'IT', escudo: 'empoli.svg' },
  { id: 'enosi-neon-ypsona-digenis-ipsona', nome: "Enosi Neon Ypsona-Digenis Ipsona", pais: 'CY', escudo: 'enosi-neon-ypsona-digenis-ipsona.png' },
  { id: 'espanyol', nome: "Espanyol", pais: 'ES', escudo: 'espanyol.svg' },
  { id: 'esporte-clube-agua-santa', nome: "Esporte Clube Água Santa", pais: 'BR', escudo: 'esporte-clube-agua-santa.png' },
  { id: 'esporte-clube-internacional-lages', nome: "Esporte Clube Internacional (Lages)", pais: 'BR', escudo: 'esporte-clube-internacional-lages.svg' },
  { id: 'esporte-clube-juventude', nome: "Esporte Clube Juventude", pais: 'BR', escudo: 'esporte-clube-juventude.png' },
  { id: 'esporte-clube-santo-andre', nome: "Esporte Clube Santo André", pais: 'BR', escudo: 'esporte-clube-santo-andre.png' },
  { id: 'esporte-clube-sao-bento', nome: "Esporte Clube São Bento", pais: 'BR', escudo: 'esporte-clube-sao-bento.png' },
  { id: 'esporte-clube-sao-jose', nome: "Esporte Clube São José", pais: 'BR', escudo: 'esporte-clube-sao-jose.png' },
  { id: 'esporte-clube-xv-de-novembro-jau', nome: "Esporte Clube XV de Novembro (Jaú)", pais: 'BR', escudo: 'esporte-clube-xv-de-novembro-jau.svg' },
  { id: 'estac-troyes', nome: "ESTAC Troyes", pais: 'FR', escudo: 'estac-troyes.png' },
  { id: 'estrela-vermelha-de-belgrado', nome: "Estrela Vermelha de Belgrado", pais: 'RS', escudo: 'estrela-vermelha-de-belgrado.svg' },
  { id: 'estudiantes', nome: "Estudiantes", pais: 'AR', escudo: 'estudiantes.svg' },
  { id: 'everton', nome: "Everton", pais: 'EN', escudo: 'everton.png' },
  { id: 'fc-anji-makhachkala', nome: "FC Anji Makhachkala", pais: 'RU', escudo: 'fc-anji-makhachkala.png' },
  { id: 'fc-dallas', nome: "FC Dallas", pais: 'US', escudo: 'fc-dallas.svg' },
  { id: 'fc-gifu', nome: "FC Gifu", pais: 'JP', escudo: 'fc-gifu.png' },
  { id: 'fc-groningen', nome: "FC Groningen", pais: 'NL', escudo: 'fc-groningen.png' },
  { id: 'fc-metz', nome: "FC Metz", pais: 'FR', escudo: 'fc-metz.svg' },
  { id: 'fc-sion', nome: "FC Sion", pais: 'CH', escudo: 'fc-sion.png' },
  { id: 'fc-tokyo', nome: "FC Tokyo", pais: 'JP', escudo: 'fc-tokyo.svg' },
  { id: 'fc-twente-enschede', nome: "FC Twente Enschede", pais: 'NL', escudo: 'fc-twente-enschede.png' },
  { id: 'fc-utrecht', nome: "FC Utrecht", pais: 'NL', escudo: 'fc-utrecht.png' },
  { id: 'fc-zenit-sao-petersburgo', nome: "FC Zenit São Petersburgo", pais: 'RU', escudo: 'fc-zenit-sao-petersburgo.svg' },
  { id: 'fenerbahce', nome: "Fenerbahçe", pais: 'TR', escudo: 'fenerbahce.png' },
  { id: 'feyenoord', nome: "Feyenoord", pais: 'NL', escudo: 'feyenoord.png' },
  { id: 'figueirense', nome: "Figueirense", pais: 'BR', escudo: 'figueirense.svg' },
  { id: 'fiorentina', nome: "Fiorentina", pais: 'IT', escudo: 'fiorentina.svg' },
  { id: 'fk-jablonec', nome: "FK Jablonec", pais: 'CZ', escudo: 'fk-jablonec.png' },
  { id: 'fk-partizan-belgrade', nome: "FK Partizan Belgrade", pais: 'RS', escudo: 'fk-partizan-belgrade.png' },
  { id: 'fk-teleoptik', nome: "FK Teleoptik", pais: 'RS', escudo: 'fk-teleoptik.png' },
  { id: 'flamengo', nome: "Flamengo", pais: 'BR', escudo: 'flamengo.svg' },
  { id: 'fleetwood-town-football-club', nome: "Fleetwood Town Football Club", pais: 'EN', escudo: 'fleetwood-town-football-club.png' },
  { id: 'fluminense', nome: "Fluminense", pais: 'BR', escudo: 'fluminense.svg' },
  { id: 'football-club-halifax-town', nome: "Football Club Halifax Town", pais: 'EN', escudo: 'football-club-halifax-town.png' },
  { id: 'fortaleza-esporte-clube', nome: "Fortaleza Esporte Clube", pais: 'BR', escudo: 'fortaleza-esporte-clube.png' },
  { id: 'fulham', nome: "Fulham", pais: 'EN', escudo: 'fulham.svg' },
  { id: 'galatasaray', nome: "Galatasaray", pais: 'TR', escudo: 'galatasaray.png' },
  { id: 'gamba-osaka', nome: "Gamba Osaka", pais: 'JP', escudo: 'gamba-osaka.svg' },
  { id: 'genoa', nome: "Genoa", pais: 'IT', escudo: 'genoa.svg' },
  { id: 'getafe', nome: "Getafe", pais: 'ES', escudo: 'getafe.png' },
  { id: 'gijon', nome: "Gijón", pais: 'ES', escudo: 'gijon.svg' },
  { id: 'gil-vicente-fc', nome: "Gil Vicente FC", pais: 'PT', escudo: 'gil-vicente-fc.png' },
  { id: 'girona', nome: "Girona", pais: 'ES', escudo: 'girona.svg' },
  { id: 'gnk-dinamo-zagreb', nome: "GNK Dinamo Zagreb", pais: 'HR', escudo: 'gnk-dinamo-zagreb.png' },
  { id: 'goias', nome: "Goias", pais: 'BR', escudo: 'goias.svg' },
  { id: 'granada', nome: "Granada", pais: 'ES', escudo: 'granada.svg' },
  { id: 'gremio', nome: "Grêmio", pais: 'BR', escudo: 'gremio.svg' },
  { id: 'guangzhou-evergrande', nome: "Guangzhou Evergrande", pais: 'CN', escudo: 'guangzhou-evergrande.png' },
  { id: 'guarani-futebol-clube', nome: "Guarani Futebol Clube", pais: 'BR', escudo: 'guarani-futebol-clube.svg' },
  { id: 'guaratingueta-futebol-ltda', nome: "Guaratinguetá Futebol Ltda.", pais: 'BR', escudo: 'guaratingueta-futebol-ltda.png' },
  { id: 'hajduk-split', nome: "Hajduk Split", pais: 'HR', escudo: 'hajduk-split.png' },
  { id: 'halmstads-bk', nome: "Halmstads BK", pais: 'SE', escudo: 'halmstads-bk.png' },
  { id: 'hamburgo', nome: "Hamburgo", pais: 'DE', escudo: 'hamburgo.svg' },
  { id: 'hangzhou-greentown-football-club', nome: "Hangzhou Greentown Football Club", pais: 'CN', escudo: 'hangzhou-greentown-football-club.png' },
  { id: 'hannover', nome: "Hannover", pais: 'DE', escudo: 'hannover.svg' },
  { id: 'hebei-football-club', nome: "Hebei Football Club", pais: 'CN', escudo: 'hebei-football-club.png' },
  { id: 'henan-songshan-longmen-football-club', nome: "Henan Songshan Longmen Football Club", pais: 'CN', escudo: 'henan-songshan-longmen-football-club.png' },
  { id: 'hoffenheim', nome: "Hoffenheim", pais: 'DE', escudo: 'hoffenheim.svg' },
  { id: 'hotspur', nome: "Hotspur", pais: 'EN', escudo: 'hotspur.svg' },
  { id: 'huracan', nome: "Huracán", pais: 'AR', escudo: 'huracan.svg' },
  { id: 'independiente', nome: "Independiente", pais: 'AR', escudo: 'independiente.svg' },
  { id: 'inter', nome: "Inter de Milão", pais: 'IT', escudo: 'inter.png' },
  { id: 'inter-miami', nome: "Inter Miami", pais: 'US', escudo: 'inter-miami.svg' },
  { id: 'internacional', nome: "Internacional", pais: 'BR', escudo: 'internacional.svg' },
  { id: 'ipswich', nome: "Ipswich", pais: 'EN', escudo: 'ipswich.png' },
  { id: 'istanbul-buyuksehir-belediyespor', nome: "İstanbul Büyükşehir Belediyespor", pais: 'TR', escudo: 'istanbul-buyuksehir-belediyespor.png' },
  { id: 'itumbiara-esporte-clube', nome: "Itumbiara Esporte Clube", pais: 'BR', escudo: 'itumbiara-esporte-clube.png' },
  { id: 'jamshedpur-fc', nome: "Jamshedpur FC", pais: 'IN', escudo: 'jamshedpur-fc.png' },
  { id: 'jeonbuk-hyundai', nome: "Jeonbuk Hyundai", pais: 'KR', escudo: 'jeonbuk-hyundai.svg' },
  { id: 'joinville', nome: "Joinville", pais: 'BR', escudo: 'joinville.png' },
  { id: 'jubiro-iwata', nome: "Jubiro Iwata", pais: 'JP', escudo: 'jubiro-iwata.png' },
  { id: 'juventus', nome: "Juventus", pais: 'IT', escudo: 'juventus.svg' },
  { id: 'karlsruher', nome: "Karlsruher", pais: 'DE', escudo: 'karlsruher.svg' },
  { id: 'kas-eupen', nome: "KAS Eupen", pais: 'BE', escudo: 'kas-eupen.png' },
  { id: 'kashima-antlers', nome: "Kashima Antlers", pais: 'JP', escudo: 'kashima-antlers.svg' },
  { id: 'kashiwa-reysol', nome: "Kashiwa Reysol", pais: 'JP', escudo: 'kashiwa-reysol.png' },
  { id: 'kawasaki-frontale', nome: "Kawasaki Frontale", pais: 'JP', escudo: 'kawasaki-frontale.png' },
  { id: 'kerala-blaster-football-club', nome: "Kerala Blaster Football Club", pais: 'IN', escudo: 'kerala-blaster-football-club.png' },
  { id: 'kitchee-sc', nome: "Kitchee SC", pais: 'HK', escudo: 'kitchee-sc.svg' },
  { id: 'kocaelispor', nome: "Kocaelispor", pais: 'TR', escudo: 'kocaelispor.png' },
  { id: 'konyaspor', nome: "Konyaspor", pais: 'TR', escudo: 'konyaspor.png' },
  { id: 'kuwait-sc', nome: "Kuwait SC", pais: 'KW', escudo: 'kuwait-sc.png' },
  { id: 'kyoto-sanga', nome: "Kyoto Sanga", pais: 'JP', escudo: 'kyoto-sanga.png' },
  { id: 'la-galaxy', nome: "LA Galaxy", pais: 'US', escudo: 'la-galaxy.svg' },
  { id: 'lazio', nome: "Lazio", pais: 'IT', escudo: 'lazio.svg' },
  { id: 'lecce', nome: "Lecce", pais: 'IT', escudo: 'lecce.png' },
  { id: 'leicester', nome: "Leicester", pais: 'EN', escudo: 'leicester.png' },
  { id: 'lekhwiya-sports-club', nome: "Lekhwiya Sports Club", pais: 'QA', escudo: 'lekhwiya-sports-club.png' },
  { id: 'lens', nome: "Lens", pais: 'FR', escudo: 'lens.png' },
  { id: 'leyton-orient-football-club', nome: "Leyton Orient Football Club", pais: 'EN', escudo: 'leyton-orient-football-club.png' },
  { id: 'liverpool', nome: "Liverpool", pais: 'EN', escudo: 'liverpool.svg' },
  { id: 'lokomotiv-moscow', nome: "Lokomotiv Moscou", pais: 'RU', escudo: 'lokomotiv-moscow.png' },
  { id: 'londrina', nome: "Londrina", pais: 'BR', escudo: 'londrina.png' },
  { id: 'los-angeles-football-club', nome: "Los Angeles Football Club", pais: 'US', escudo: 'los-angeles-football-club.svg' },
  { id: 'lyon', nome: "Olympique Lyonnais", pais: 'FR', escudo: 'lyon.svg' },
  { id: 'machida-zelvia', nome: "Machida Zelvia", pais: 'JP', escudo: 'machida-zelvia.svg' },
  { id: 'madureira-esporte-clube', nome: "Madureira Esporte Clube", pais: 'BR', escudo: 'madureira-esporte-clube.svg' },
  { id: 'mallorca', nome: "Mallorca", pais: 'ES', escudo: 'mallorca.png' },
  { id: 'man-city', nome: "Man City", pais: 'EN', escudo: 'man-city.png' },
  { id: 'manchester-city', nome: "Manchester City", pais: 'EN', escudo: 'manchester-city.png' },
  { id: 'manchester-united', nome: "Manchester United", pais: 'EN', escudo: 'manchester-united.png' },
  { id: 'manchete-futebol-clube-do-recife', nome: "Manchete Futebol Clube do Recife", pais: 'BR', escudo: 'manchete-futebol-clube-do-recife.png' },
  { id: 'marseille', nome: "Olympique de Marseille", pais: 'FR', escudo: 'marseille.svg' },
  { id: 'melbourne-city-football-club', nome: "Melbourne City Football Club", pais: 'AU', escudo: 'melbourne-city-football-club.png' },
  { id: 'milan', nome: "Milan", pais: 'IT', escudo: 'milan.svg' },
  { id: 'millonarios', nome: "millonarios", pais: 'CO', escudo: 'millonarios.png' },
  { id: 'millwall-football-club', nome: "Millwall Football Club", pais: 'EN', escudo: 'millwall-football-club.png' },
  { id: 'milton-keynes-dons-football-club', nome: "Milton Keynes Dons Football Club", pais: 'EN', escudo: 'milton-keynes-dons-football-club.png' },
  { id: 'mke-ankaragucu', nome: "MKE Ankaragücü", pais: 'TR', escudo: 'mke-ankaragucu.png' },
  { id: 'mogi-mirim', nome: "Mogi Mirim", pais: 'BR', escudo: 'mogi-mirim.svg' },
  { id: 'monaco', nome: "Monaco", pais: 'FR', escudo: 'monaco.svg' },
  { id: 'monza', nome: "Monza", pais: 'IT', escudo: 'monza.svg' },
  { id: 'moto-club-de-sao-luis', nome: "Moto Club de São Luís", pais: 'BR', escudo: 'moto-club-de-sao-luis.png' },
  { id: 'mumbai-city-football-club', nome: "Mumbai City Football Club", pais: 'IN', escudo: 'mumbai-city-football-club.png' },
  { id: 'murici-futebol-clube', nome: "Murici Futebol Clube", pais: 'BR', escudo: 'murici-futebol-clube.png' },
  { id: 'nacional', nome: "nacional", pais: 'UY', escudo: 'nacional.png' },
  { id: 'nagoya-grampus', nome: "Nagoya Grampus", pais: 'JP', escudo: 'nagoya-grampus.svg' },
  { id: 'nantes', nome: "Nantes", pais: 'FR', escudo: 'nantes.svg' },
  { id: 'napoli', nome: "Napoli", pais: 'IT', escudo: 'napoli.svg' },
  { id: 'nautico', nome: "Nautico", pais: 'BR', escudo: 'nautico.svg' },
  { id: 'new-york-cosmos', nome: "New York Cosmos", pais: 'US', escudo: 'new-york-cosmos.png' },
  { id: 'newcastle', nome: "Newcastle", pais: 'EN', escudo: 'newcastle.png' },
  { id: 'newell-s', nome: "Newell's", pais: 'AR', escudo: 'newell-s.svg' },
  { id: 'nice', nome: "Nice", pais: 'FR', escudo: 'nice.png' },
  { id: 'nk-inter-zapresic', nome: "NK Inter Zaprešić", pais: 'HR', escudo: 'nk-inter-zapresic.png' },
  { id: 'norwich', nome: "Norwich", pais: 'EN', escudo: 'norwich.png' },
  { id: 'nottingham', nome: "Nottingham", pais: 'EN', escudo: 'nottingham.svg' },
  { id: 'nova-iguacu-futebol-clube', nome: "Nova Iguaçu Futebol Clube", pais: 'BR', escudo: 'nova-iguacu-futebol-clube.png' },
  { id: 'odisha-fc', nome: "Odisha FC", pais: 'IN', escudo: 'odisha-fc.png' },
  { id: 'oita-trinita', nome: "Oita Trinita", pais: 'JP', escudo: 'oita-trinita.svg' },
  { id: 'olaria-atletico-clube', nome: "Olaria Atlético Clube", pais: 'BR', escudo: 'olaria-atletico-clube.png' },
  { id: 'olympiacos-piraeus', nome: "Olympiacos Piraeus", pais: 'GR', escudo: 'olympiacos-piraeus.png' },
  { id: 'olympique-lyon', nome: "Olympique Lyon", pais: 'FR', escudo: 'olympique-lyon.png' },
  { id: 'omiya-ardija', nome: "Omiya Ardija", pais: 'JP', escudo: 'omiya-ardija.svg' },
  { id: 'operario-ferroviario-esporte-clube', nome: "Operário Ferroviário Esporte Clube", pais: 'BR', escudo: 'operario-ferroviario-esporte-clube.png' },
  { id: 'orlando-city', nome: "Orlando City", pais: 'US', escudo: 'orlando-city.svg' },
  { id: 'osasuna', nome: "Osasuna", pais: 'ES', escudo: 'osasuna.svg' },
  { id: 'oxford-united-football-club', nome: "Oxford United Football Club", pais: 'EN', escudo: 'oxford-united-football-club.png' },
  { id: 'pafos-fc', nome: "Pafos FC", pais: 'CY', escudo: 'pafos-fc.png' },
  { id: 'palermo-football-club', nome: "Palermo Football Club", pais: 'IT', escudo: 'palermo-football-club.png' },
  { id: 'palmeiras', nome: "Palmeiras", pais: 'BR', escudo: 'palmeiras.svg' },
  { id: 'panathinaikos', nome: "Panathinaikos", pais: 'GR', escudo: 'panathinaikos.png' },
  { id: 'panionios', nome: "Panionios", pais: 'GR', escudo: 'panionios.png' },
  { id: 'paok-thessaloniki', nome: "PAOK Thessaloniki", pais: 'GR', escudo: 'paok-thessaloniki.png' },
  { id: 'parma', nome: "Parma", pais: 'IT', escudo: 'parma.svg' },
  { id: 'paulinia-futebol-clube', nome: "Paulínia Futebol Clube", pais: 'BR', escudo: 'paulinia-futebol-clube.png' },
  { id: 'penarol', nome: "penarol", pais: 'UY', escudo: 'penarol.png' },
  { id: 'perugia-calcio', nome: "Perugia Calcio", pais: 'IT', escudo: 'perugia-calcio.png' },
  { id: 'pescara-calcio', nome: "Pescara Calcio", pais: 'IT', escudo: 'pescara-calcio.png' },
  { id: 'pisa', nome: "Pisa", pais: 'IT', escudo: 'pisa.svg' },
  { id: 'ponte-preta', nome: "Ponte Preta", pais: 'BR', escudo: 'ponte-preta.svg' },
  { id: 'porto', nome: "Porto", pais: 'PT', escudo: 'porto.png' },
  { id: 'portuguesa', nome: "Portuguesa", pais: 'BR', escudo: 'portuguesa.png' },
  { id: 'preston-north-end-football-club', nome: "Preston North End Football Club", pais: 'EN', escudo: 'preston-north-end-football-club.png' },
  { id: 'psg', nome: "Paris Saint-Germain", pais: 'FR', escudo: 'psg.png' },
  { id: 'psv', nome: "PSV", pais: 'NL', escudo: 'psv.png' },
  { id: 'queretaro', nome: "queretaro", pais: 'MX', escudo: 'queretaro.png' },
  { id: 'rangers-football-club', nome: "Rangers Football Club", pais: 'EN', escudo: 'rangers-football-club.png' },
  { id: 'ravenna-calcio', nome: "Ravenna Calcio", pais: 'IT', escudo: 'ravenna-calcio.png' },
  { id: 'reading', nome: "Reading", pais: 'EN', escudo: 'reading.png' },
  { id: 'real-betis', nome: "Real Betis", pais: 'ES', escudo: 'real-betis.svg' },
  { id: 'real-madrid', nome: "Real Madrid", pais: 'ES', escudo: 'real-madrid.png' },
  { id: 'red-bull-new-york', nome: "Red Bull New York", pais: 'US', escudo: 'red-bull-new-york.svg' },
  { id: 'rio-ave-fc', nome: "Rio Ave FC", pais: 'PT', escudo: 'rio-ave-fc.png' },
  { id: 'rio-claro-futebol-clube', nome: "Rio Claro Futebol Clube", pais: 'BR', escudo: 'rio-claro-futebol-clube.svg' },
  { id: 'rio-preto-esporte-clube', nome: "Rio Preto Esporte Clube", pais: 'BR', escudo: 'rio-preto-esporte-clube.png' },
  { id: 'river-plate', nome: "River Plate", pais: 'AR', escudo: 'river-plate.svg' },
  { id: 'rkc-waalwijk', nome: "RKC Waalwijk", pais: 'NL', escudo: 'rkc-waalwijk.png' },
  { id: 'roma', nome: "Roma", pais: 'IT', escudo: 'roma.png' },
  { id: 'rosario-central', nome: "Rosario Central", pais: 'AR', escudo: 'rosario-central.svg' },
  { id: 'rotherham-united-football-club', nome: "Rotherham United Football Club", pais: 'EN', escudo: 'rotherham-united-football-club.png' },
  { id: 'rsc-anderlecht', nome: "RSC Anderlecht", pais: 'BE', escudo: 'rsc-anderlecht.png' },
  { id: 'saint-etienne', nome: "Saint-Étienne", pais: 'FR', escudo: 'saint-etienne.svg' },
  { id: 'samsunspor', nome: "Samsunspor", pais: 'TR', escudo: 'samsunspor.png' },
  { id: 'sanfrecce-hiroshima', nome: "Sanfrecce Hiroshima", pais: 'JP', escudo: 'sanfrecce-hiroshima.png' },
  { id: 'santa-cruz', nome: "Santa Cruz", pais: 'BR', escudo: 'santa-cruz.svg' },
  { id: 'santos', nome: "Santos", pais: 'BR', escudo: 'santos.svg' },
  { id: 'sao-bernardo-futebol-clube', nome: "São Bernardo Futebol Clube", pais: 'BR', escudo: 'sao-bernardo-futebol-clube.png' },
  { id: 'sao-jose-esporte-clube', nome: "São José Esporte Clube", pais: 'BR', escudo: 'sao-jose-esporte-clube.png' },
  { id: 'sao-paulo', nome: "São Paulo", pais: 'BR', escudo: 'sao-paulo.svg' },
  { id: 'sassuolo', nome: "Sassuolo", pais: 'IT', escudo: 'sassuolo.svg' },
  { id: 'sc-telstar', nome: "SC Telstar", pais: 'NL', escudo: 'sc-telstar.png' },
  { id: 'schalke', nome: "Schalke 04", pais: 'DE', escudo: 'schalke.svg' },
  { id: 'seattle-sounders', nome: "Seattle Sounders", pais: 'US', escudo: 'seattle-sounders.svg' },
  { id: 'servette-fc', nome: "Servette FC", pais: 'CH', escudo: 'servette-fc.png' },
  { id: 'sevilla', nome: "Sevilla", pais: 'ES', escudo: 'sevilla.png' },
  { id: 'shakhtar', nome: "Shakhtar Donetsk", pais: 'UA', escudo: 'shakhtar.png' },
  { id: 'shanghai-shenhua', nome: "Shanghai Shenhua", pais: 'CN', escudo: 'shanghai-shenhua.png' },
  { id: 'shanghai-sipg', nome: "Shanghai Port", pais: 'CN', escudo: 'shanghai-sipg.png' },
  { id: 'sharjah-fc', nome: "Sharjah FC", pais: 'AE', escudo: 'sharjah-fc.png' },
  { id: 'sheffield-wednesday', nome: "Sheffield Wednesday", pais: 'EN', escudo: 'sheffield-wednesday.png' },
  { id: 'shimizu-s-pulse', nome: "Shimizu S-Pulse", pais: 'JP', escudo: 'shimizu-s-pulse.svg' },
  { id: 'shonan-bellmare', nome: "Shonan Bellmare", pais: 'JP', escudo: 'shonan-bellmare.svg' },
  { id: 'sinop-futebol-clube', nome: "Sinop Futebol Clube", pais: 'BR', escudo: 'sinop-futebol-clube.png' },
  { id: 'siracusa-calcio-1924', nome: "Siracusa Calcio 1924", pais: 'IT', escudo: 'siracusa-calcio-1924.png' },
  { id: 'sivasspor', nome: "Sivasspor", pais: 'TR', escudo: 'sivasspor.png' },
  { id: 'sk-sigma-olomouc', nome: "SK Sigma Olomouc", pais: 'CZ', escudo: 'sk-sigma-olomouc.png' },
  { id: 'sobradinho-esporte-clube', nome: "Sobradinho Esporte Clube", pais: 'BR', escudo: 'sobradinho-esporte-clube.png' },
  { id: 'sociedade-desportiva-juazeirense', nome: "Sociedade Desportiva Juazeirense", pais: 'BR', escudo: 'sociedade-desportiva-juazeirense.png' },
  { id: 'southampton', nome: "Southampton", pais: 'EN', escudo: 'southampton.png' },
  { id: 'spartak', nome: "Spartak", pais: 'RS', escudo: 'spartak.png' },
  { id: 'spartak-moscow', nome: "Spartak Moscow", pais: 'RU', escudo: 'spartak-moscow.png' },
  { id: 'sport', nome: "Sport Recife", pais: 'BR', escudo: 'sport.png' },
  { id: 'sport-boys-association', nome: "Sport Boys Association", pais: 'PE', escudo: 'sport-boys-association.svg' },
  { id: 'sporting-cp', nome: "Sporting", pais: 'PT', escudo: 'sporting-cp.png' },
  { id: 'standard-liege', nome: "Standard Liège", pais: 'BE', escudo: 'standard-liege.png' },
  { id: 'stocksbridge-park-steels-f-c', nome: "Stocksbridge Park Steels F.C.", pais: 'EN', escudo: 'stocksbridge-park-steels-f-c.png' },
  { id: 'stoke-city-football-club', nome: "Stoke City Football Club", pais: 'EN', escudo: 'stoke-city-football-club.png' },
  { id: 'stuttgart', nome: "Stuttgart", pais: 'DE', escudo: 'stuttgart.svg' },
  { id: 'sunderland', nome: "Sunderland", pais: 'EN', escudo: 'sunderland.svg' },
  { id: 'swindon-town-football-club', nome: "Swindon Town Football Club", pais: 'EN', escudo: 'swindon-town-football-club.png' },
  { id: 'sydney-football-club', nome: "Sydney Football Club", pais: 'AU', escudo: 'sydney-football-club.png' },
  { id: 'sydney-united-58-football-club', nome: "Sydney United 58 Football Club", pais: 'AU', escudo: 'sydney-united-58-football-club.png' },
  { id: 'tianjin-tianhai-football-club', nome: "Tianjin Tianhai Football Club", pais: 'CN', escudo: 'tianjin-tianhai-football-club.png' },
  { id: 'tigres', nome: "tigres", pais: 'MX', escudo: 'tigres.png' },
  { id: 'tokushima-vortis', nome: "Tokushima Vortis", pais: 'JP', escudo: 'tokushima-vortis.svg' },
  { id: 'tokyo-verdy', nome: "Tokyo Verdy", pais: 'JP', escudo: 'tokyo-verdy.svg' },
  { id: 'toluca', nome: "toluca", pais: 'MX', escudo: 'toluca.png' },
  { id: 'tombense-futebol-clube', nome: "Tombense Futebol Clube", pais: 'BR', escudo: 'tombense-futebol-clube.svg' },
  { id: 'torino', nome: "Torino", pais: 'IT', escudo: 'torino.svg' },
  { id: 'toulouse', nome: "Toulouse", pais: 'FR', escudo: 'toulouse.png' },
  { id: 'trabzonspor', nome: "Trabzonspor", pais: 'TR', escudo: 'trabzonspor.png' },
  { id: 'tupi', nome: "Tupi", pais: 'BR', escudo: 'tupi.svg' },
  { id: 'tupynambas-futebol-clube', nome: "Tupynambás Futebol Clube", pais: 'BR', escudo: 'tupynambas-futebol-clube.png' },
  { id: 'u-s-livorno-1915', nome: "U.S. Livorno 1915", pais: 'IT', escudo: 'u-s-livorno-1915.png' },
  { id: 'uberlandia-esporte-clube', nome: "Uberlândia Esporte Clube", pais: 'BR', escudo: 'uberlandia-esporte-clube.png' },
  { id: 'udinese', nome: "Udinese", pais: 'IT', escudo: 'udinese.png' },
  { id: 'uniao-sao-joao-esporte-clube', nome: "União São João Esporte Clube", pais: 'BR', escudo: 'uniao-sao-joao-esporte-clube.png' },
  { id: 'unione-sportiva-catanzaro', nome: "Unione Sportiva Catanzaro", pais: 'IT', escudo: 'unione-sportiva-catanzaro.png' },
  { id: 'united-football-club', nome: "United Football Club", pais: 'AE', escudo: 'united-football-club.svg' },
  { id: 'urawa-red-diamonds', nome: "Urawa Red Diamonds", pais: 'JP', escudo: 'urawa-red-diamonds.png' },
  { id: 'us-salernitana-1919', nome: "US Salernitana 1919", pais: 'IT', escudo: 'us-salernitana-1919.png' },
  { id: 'valencia', nome: "Valencia", pais: 'ES', escudo: 'valencia.svg' },
  { id: 'vallecano', nome: "Vallecano", pais: 'ES', escudo: 'vallecano.png' },
  { id: 'vasco', nome: "Vasco da Gama", pais: 'BR', escudo: 'vasco.svg' },
  { id: 'velez-sarsfield', nome: "Vélez Sarsfield", pais: 'AR', escudo: 'velez-sarsfield.svg' },
  { id: 'venezia', nome: "Venezia", pais: 'IT', escudo: 'venezia.svg' },
  { id: 'ventforet-kofu', nome: "Ventforet Kofu", pais: 'JP', escudo: 'ventforet-kofu.png' },
  { id: 'vestel-manisaspor', nome: "Vestel Manisaspor", pais: 'TR', escudo: 'vestel-manisaspor.png' },
  { id: 'vila-nova', nome: "Vila Nova", pais: 'BR', escudo: 'vila-nova.svg' },
  { id: 'villarreal', nome: "Villarreal", pais: 'ES', escudo: 'villarreal.svg' },
  { id: 'vissel-kobe', nome: "Vissel Kobe", pais: 'JP', escudo: 'vissel-kobe.svg' },
  { id: 'vitoria', nome: "Vitória", pais: 'BR', escudo: 'vitoria.svg' },
  { id: 'watford-fc', nome: "Watford FC", pais: 'EN', escudo: 'watford-fc.png' },
  { id: 'werder-bremen', nome: "Werder Bremen", pais: 'DE', escudo: 'werder-bremen.png' },
  { id: 'west-ham', nome: "West Ham", pais: 'EN', escudo: 'west-ham.svg' },
  { id: 'western-sydney-wanderers-football-club', nome: "Western Sydney Wanderers Football Club", pais: 'AU', escudo: 'western-sydney-wanderers-football-club.png' },
  { id: 'western-united', nome: "Western United", pais: 'EN', escudo: 'western-united.svg' },
  { id: 'wigan-athletic-football-club', nome: "Wigan Athletic Football Club", pais: 'EN', escudo: 'wigan-athletic-football-club.png' },
  { id: 'willem-ii', nome: "Willem II", pais: 'NL', escudo: 'willem-ii.png' },
  { id: 'wisla-krakow', nome: "Wisla Kraków", pais: 'PL', escudo: 'wisla-krakow.png' },
  { id: 'wolfsburg', nome: "Wolfsburg", pais: 'DE', escudo: 'wolfsburg.svg' },
  { id: 'wolverhampton-wanderers', nome: "Wolverhampton Wanderers", pais: 'EN', escudo: 'wolverhampton-wanderers.png' },
  { id: 'wuhan-three-towns-football-club', nome: "Wuhan Three Towns Football Club", pais: 'CN', escudo: 'wuhan-three-towns-football-club.png' },
  { id: 'yokohama-fc', nome: "Yokohama FC", pais: 'JP', escudo: 'yokohama-fc.png' },
  { id: 'yokohama-marinos', nome: "Yokohama Marinos", pais: 'JP', escudo: 'yokohama-marinos.png' },
  { id: 'zaragoza', nome: "Zaragoza", pais: 'ES', escudo: 'zaragoza.png' },
]

export const CLUBE_POR_ID = new Map(CLUBES.map((c) => [c.id, c]))
