// GERADO POR scripts/construir-catalogo.mjs — não edite à mão.
// Só os clubes em uso pelos jogadores; o catálogo completo, para consultar
// ao escrever uma carreira nova, está em scripts/catalogo-completo.json.
// Nome e id dos clubes usados pelos jogadores vivem em scripts/clubes-canonicos.mjs.
import type { Clube } from './tipos'

export const CLUBES: Clube[] = [
  { id: 'aarhus-gf', nome: "Aarhus GF", pais: 'DK', escudo: 'aarhus-gf.png' },
  { id: 'acr-siena-1904', nome: "ACR Siena 1904", pais: 'IT', escudo: 'acr-siena-1904.png' },
  { id: 'adana-demirspor', nome: "Adana Demirspor", pais: 'TR', escudo: 'adana-demirspor.png' },
  { id: 'ajax', nome: "Ajax", pais: 'NL', escudo: 'ajax.png' },
  { id: 'al-ahli-saudi', nome: "Al-Ahli", pais: 'SA', escudo: 'al-ahli-saudi.png' },
  { id: 'al-ahli-sports-club', nome: "Al-Ahli Sports Club", pais: 'QA', escudo: 'al-ahli-sports-club.png' },
  { id: 'al-arabi-sports-club', nome: "Al-Arabi Sports Club", pais: 'QA', escudo: 'al-arabi-sports-club.png' },
  { id: 'al-ettifaq', nome: "Al-Ettifaq", pais: 'SA', escudo: 'al-ettifaq.svg' },
  { id: 'al-gharafa', nome: "Al-Gharafa", pais: 'QA', escudo: 'al-gharafa.png' },
  { id: 'al-hilal', nome: "Al-Hilal", pais: 'SA', escudo: 'al-hilal.svg' },
  { id: 'al-ittihad', nome: "Al-Ittihad", pais: 'SA', escudo: 'al-ittihad.svg' },
  { id: 'al-nassr', nome: "Al-Nassr", pais: 'SA', escudo: 'al-nassr.svg' },
  { id: 'al-qadsiah', nome: "Al-Qadsiah", pais: 'SA', escudo: 'al-qadsiah.svg' },
  { id: 'al-rayyan-sports-club', nome: "Al-Rayyan Sports Club", pais: 'QA', escudo: 'al-rayyan-sports-club.png' },
  { id: 'al-sadd-sports-club', nome: "Al-Sadd Sports Club", pais: 'QA', escudo: 'al-sadd-sports-club.png' },
  { id: 'al-shabab', nome: "Al-Shabab", pais: 'SA', escudo: 'al-shabab.svg' },
  { id: 'al-wahda-sports-cultural-club', nome: "Al-Wahda Sports Cultural Club", pais: 'AE', escudo: 'al-wahda-sports-cultural-club.png' },
  { id: 'alaves', nome: "Alavés", pais: 'ES', escudo: 'alaves.svg' },
  { id: 'albacete', nome: "Albacete", pais: 'ES', escudo: 'albacete.svg' },
  { id: 'albirex-niigata', nome: "Albirex Niigata", pais: 'JP', escudo: 'albirex-niigata.svg' },
  { id: 'alfreton-town-football-club', nome: "Alfreton Town Football Club", pais: 'EN', escudo: 'alfreton-town-football-club.png' },
  { id: 'america', nome: "america", pais: 'MX', escudo: 'america.png' },
  { id: 'america-futebol-clube-belo-horizonte', nome: "América Futebol Clube (Belo Horizonte)", pais: 'BR', escudo: 'america-futebol-clube-belo-horizonte.png' },
  { id: 'america-futebol-clube-rio-grande-do-norte', nome: "América Futebol Clube (Rio Grande do Norte)", pais: 'BR', escudo: 'america-futebol-clube-rio-grande-do-norte.svg' },
  { id: 'antalyaspor', nome: "Antalyaspor", pais: 'TR', escudo: 'antalyaspor.png' },
  { id: 'apollon-smyrnis', nome: "Apollon Smyrnis", pais: 'GR', escudo: 'apollon-smyrnis.png' },
  { id: 'army-united-football-club', nome: "Army United Football Club", pais: 'TH', escudo: 'army-united-football-club.png' },
  { id: 'arsenal', nome: "Arsenal", pais: 'EN', escudo: 'arsenal.svg' },
  { id: 'asociacion-deportivo-pasto', nome: "Asociación Deportivo Pasto", pais: 'CO', escudo: 'asociacion-deportivo-pasto.png' },
  { id: 'associacao-atletica-internacional-limeira', nome: "Associação Atlética Internacional (Limeira)", pais: 'BR', escudo: 'associacao-atletica-internacional-limeira.png' },
  { id: 'associacao-atletica-sao-bento-sao-paulo', nome: "Associação Atlética São Bento (São Paulo)", pais: 'BR', escudo: 'associacao-atletica-sao-bento-sao-paulo.png' },
  { id: 'associacao-desportiva-sao-caetano', nome: "Associação Desportiva São Caetano", pais: 'BR', escudo: 'associacao-desportiva-sao-caetano.png' },
  { id: 'associazione-calcio-cesena', nome: "Associazione Calcio Cesena", pais: 'IT', escudo: 'associazione-calcio-cesena.png' },
  { id: 'associazione-calcio-mantova', nome: "Associazione Calcio Mantova", pais: 'IT', escudo: 'associazione-calcio-mantova.svg' },
  { id: 'associazione-calcio-reggiana-1919', nome: "Associazione Calcio Reggiana 1919", pais: 'IT', escudo: 'associazione-calcio-reggiana-1919.png' },
  { id: 'aston-villa', nome: "Aston Villa", pais: 'EN', escudo: 'aston-villa.png' },
  { id: 'atalanta', nome: "Atalanta", pais: 'IT', escudo: 'atalanta.svg' },
  { id: 'atlante', nome: "atlante", pais: 'MX', escudo: 'atlante.png' },
  { id: 'atletico-madrid', nome: "Atlético de Madrid", pais: 'ES', escudo: 'atletico-madrid.svg' },
  { id: 'audax-italiano', nome: "Audax Italiano", pais: 'CL', escudo: 'audax-italiano.png' },
  { id: 'augsburg', nome: "Augsburg", pais: 'DE', escudo: 'augsburg.svg' },
  { id: 'austria-vienna', nome: "Austria Vienna", pais: 'AT', escudo: 'austria-vienna.png' },
  { id: 'avai', nome: "Avai", pais: 'BR', escudo: 'avai.svg' },
  { id: 'avispa-fukuoka', nome: "Avispa Fukuoka", pais: 'JP', escudo: 'avispa-fukuoka.png' },
  { id: 'bahia', nome: "Bahia", pais: 'BR', escudo: 'bahia.svg' },
  { id: 'ballymena-united', nome: "Ballymena United", pais: 'EN', escudo: 'ballymena-united.png' },
  { id: 'banfield', nome: "Banfield", pais: 'AR', escudo: 'banfield.svg' },
  { id: 'bangu-atletico-clube', nome: "Bangu Atlético Clube", pais: 'BR', escudo: 'bangu-atletico-clube.svg' },
  { id: 'barcelona', nome: "Barcelona", pais: 'ES', escudo: 'barcelona.svg' },
  { id: 'barnet-football-club', nome: "Barnet Football Club", pais: 'EN', escudo: 'barnet-football-club.png' },
  { id: 'basel', nome: "Basel", pais: 'CH', escudo: 'basel.png' },
  { id: 'batatais-futebol-clube', nome: "Batatais Futebol Clube", pais: 'BR', escudo: 'batatais-futebol-clube.png' },
  { id: 'bayer-leverkusen', nome: "Bayer Leverkusen", pais: 'DE', escudo: 'bayer-leverkusen.png' },
  { id: 'bayern', nome: "Bayern de Munique", pais: 'DE', escudo: 'bayern.svg' },
  { id: 'beijing-guoan-football-club', nome: "Beijing Guoan Football Club", pais: 'CN', escudo: 'beijing-guoan-football-club.png' },
  { id: 'benfica', nome: "Benfica", pais: 'PT', escudo: 'benfica.png' },
  { id: 'besiktas', nome: "Beşiktaş", pais: 'TR', escudo: 'besiktas.png' },
  { id: 'bg-pathum-united-football-club', nome: "BG Pathum United Football Club", pais: 'TH', escudo: 'bg-pathum-united-football-club.png' },
  { id: 'birmingham-city', nome: "Birmingham City", pais: 'EN', escudo: 'birmingham-city.png' },
  { id: 'blackburn-rovers-football-club', nome: "Blackburn Rovers Football Club", pais: 'EN', escudo: 'blackburn-rovers-football-club.png' },
  { id: 'boca-juniors', nome: "Boca Juniors", pais: 'AR', escudo: 'boca-juniors.svg' },
  { id: 'bochum', nome: "Bochum", pais: 'DE', escudo: 'bochum.svg' },
  { id: 'bolton-wanderers-football-club', nome: "Bolton Wanderers Football Club", pais: 'EN', escudo: 'bolton-wanderers-football-club.png' },
  { id: 'bonsucesso-futebol-clube', nome: "Bonsucesso Futebol Clube", pais: 'BR', escudo: 'bonsucesso-futebol-clube.png' },
  { id: 'bor-m-gladbach', nome: "Bor. M'gladbach", pais: 'DE', escudo: 'bor-m-gladbach.png' },
  { id: 'bordeaux', nome: "Bordeaux", pais: 'FR', escudo: 'bordeaux.png' },
  { id: 'botafogo', nome: "Botafogo", pais: 'BR', escudo: 'botafogo.svg' },
  { id: 'botafogo-futebol-clube-ribeirao-preto', nome: "Botafogo Futebol Clube (Ribeirão Preto)", pais: 'BR', escudo: 'botafogo-futebol-clube-ribeirao-preto.png' },
  { id: 'bournemouth', nome: "Bournemouth", pais: 'EN', escudo: 'bournemouth.svg' },
  { id: 'bradford-city-association-football-club', nome: "Bradford City Association Football Club", pais: 'EN', escudo: 'bradford-city-association-football-club.png' },
  { id: 'brentford', nome: "Brentford", pais: 'EN', escudo: 'brentford.svg' },
  { id: 'brescia', nome: "Brescia", pais: 'IT', escudo: 'brescia.png' },
  { id: 'brighton', nome: "Brighton", pais: 'EN', escudo: 'brighton.svg' },
  { id: 'brisbane-roar-football-club', nome: "Brisbane Roar Football Club", pais: 'AU', escudo: 'brisbane-roar-football-club.png' },
  { id: 'bristol-city-football-club', nome: "Bristol City Football Club", pais: 'EN', escudo: 'bristol-city-football-club.png' },
  { id: 'brondby-if', nome: "Bröndby IF", pais: 'DK', escudo: 'brondby-if.png' },
  { id: 'burnley', nome: "Burnley", pais: 'EN', escudo: 'burnley.svg' },
  { id: 'burton-albion-football-club', nome: "Burton Albion Football Club", pais: 'EN', escudo: 'burton-albion-football-club.png' },
  { id: 'cagliari', nome: "Cagliari", pais: 'IT', escudo: 'cagliari.svg' },
  { id: 'calcio-padova', nome: "Calcio Padova", pais: 'IT', escudo: 'calcio-padova.png' },
  { id: 'cambridge-united-football-club', nome: "Cambridge United Football Club", pais: 'EN', escudo: 'cambridge-united-football-club.png' },
  { id: 'campinas-esporte-clube-mato-grosso', nome: "Campinas Esporte Clube (Mato Grosso)", pais: 'BR', escudo: 'campinas-esporte-clube-mato-grosso.png' },
  { id: 'cardiff-city-football-club', nome: "Cardiff City Football Club", pais: 'EN', escudo: 'cardiff-city-football-club.png' },
  { id: 'carlisle-united-football-club', nome: "Carlisle United Football Club", pais: 'EN', escudo: 'carlisle-united-football-club.png' },
  { id: 'catania-fc', nome: "Catania FC", pais: 'IT', escudo: 'catania-fc.png' },
  { id: 'ceara', nome: "Ceara", pais: 'BR', escudo: 'ceara.svg' },
  { id: 'celtic-football-club', nome: "Celtic Football Club", pais: 'EN', escudo: 'celtic-football-club.png' },
  { id: 'central-cordoba', nome: "Central Córdoba", pais: 'AR', escudo: 'central-cordoba.svg' },
  { id: 'cerezo-osaka', nome: "Cerezo Osaka", pais: 'JP', escudo: 'cerezo-osaka.png' },
  { id: 'cf-monterrey', nome: "CF Monterrey", pais: 'MX', escudo: 'cf-monterrey.svg' },
  { id: 'cf-montreal-q167615', nome: "CF Montréal", pais: 'CA', escudo: 'cf-montreal-q167615.svg' },
  { id: 'cf-pachuca', nome: "CF Pachuca", pais: 'MX', escudo: 'cf-pachuca.svg' },
  { id: 'chapecoense', nome: "Chapecoense", pais: 'BR', escudo: 'chapecoense.png' },
  { id: 'chelsea', nome: "Chelsea", pais: 'EN', escudo: 'chelsea.png' },
  { id: 'chennaiyin-football-club', nome: "Chennaiyin Football Club", pais: 'IN', escudo: 'chennaiyin-football-club.png' },
  { id: 'chicago-fire', nome: "Chicago Fire", pais: 'US', escudo: 'chicago-fire.svg' },
  { id: 'club-alianza-lima', nome: "Club Alianza Lima", pais: 'PE', escudo: 'club-alianza-lima.svg' },
  { id: 'club-athletico-paranaense', nome: "Club Athletico Paranaense", pais: 'BR', escudo: 'club-athletico-paranaense.png' },
  { id: 'club-atletico-rentistas', nome: "Club Atlético Rentistas", pais: 'UY', escudo: 'club-atletico-rentistas.png' },
  { id: 'club-cerro-porteno-presidente-franco', nome: "Club Cerro Porteño (Presidente Franco)", pais: 'PY', escudo: 'club-cerro-porteno-presidente-franco.png' },
  { id: 'club-de-deportes-antofagasta', nome: "Club de Deportes Antofagasta", pais: 'CL', escudo: 'club-de-deportes-antofagasta.png' },
  { id: 'club-deportes-tolima', nome: "Club Deportes Tolima", pais: 'CO', escudo: 'club-deportes-tolima.png' },
  { id: 'club-deportivo-atalaya', nome: "Club Deportivo Atalaya", pais: 'AR', escudo: 'club-deportivo-atalaya.png' },
  { id: 'club-deportivo-guadalajara', nome: "Club Deportivo Guadalajara", pais: 'MX', escudo: 'club-deportivo-guadalajara.png' },
  { id: 'club-deportivo-la-equidad', nome: "Club Deportivo La Equidad", pais: 'CO', escudo: 'club-deportivo-la-equidad.svg' },
  { id: 'club-nacional', nome: "Club Nacional", pais: 'PY', escudo: 'club-nacional.png' },
  { id: 'club-rubio-nu', nome: "Club Rubio Ñu", pais: 'PY', escudo: 'club-rubio-nu.png' },
  { id: 'club-social-y-deportivo-dorados-de-sinaloa', nome: "Club Social y Deportivo Dorados de Sinaloa", pais: 'MX', escudo: 'club-social-y-deportivo-dorados-de-sinaloa.png' },
  { id: 'club-universidad-de-chile', nome: "Club Universidad de Chile", pais: 'CL', escudo: 'club-universidad-de-chile.png' },
  { id: 'club-universidad-nacional', nome: "Club Universidad Nacional", pais: 'MX', escudo: 'club-universidad-nacional.png' },
  { id: 'clube-atletico-juventus', nome: "Clube Atlético Juventus", pais: 'BR', escudo: 'clube-atletico-juventus.png' },
  { id: 'clube-atletico-mineiro', nome: "Clube Atlético Mineiro", pais: 'BR', escudo: 'clube-atletico-mineiro.svg' },
  { id: 'clube-atletico-taboao-da-serra', nome: "Clube Atlético Taboão da Serra", pais: 'BR', escudo: 'clube-atletico-taboao-da-serra.png' },
  { id: 'clube-do-remo', nome: "Clube do Remo", pais: 'BR', escudo: 'clube-do-remo.png' },
  { id: 'colo-colo', nome: "Colo-Colo", pais: 'CL', escudo: 'colo-colo.png' },
  { id: 'colon', nome: "Colón", pais: 'AR', escudo: 'colon.svg' },
  { id: 'como', nome: "Como", pais: 'IT', escudo: 'como.svg' },
  { id: 'consadole-sapporo', nome: "Consadole Sapporo", pais: 'JP', escudo: 'consadole-sapporo.png' },
  { id: 'corinthians', nome: "Corinthians", pais: 'BR', escudo: 'corinthians.png' },
  { id: 'coritiba', nome: "Coritiba", pais: 'BR', escudo: 'coritiba.svg' },
  { id: 'corporacion-deportiva-club-atletico-nacional', nome: "Corporación Deportiva Club Atlético Nacional", pais: 'CO', escudo: 'corporacion-deportiva-club-atletico-nacional.svg' },
  { id: 'coventry-city', nome: "Coventry City", pais: 'EN', escudo: 'coventry-city.png' },
  { id: 'cremonese', nome: "Cremonese", pais: 'IT', escudo: 'cremonese.svg' },
  { id: 'cruzeiro', nome: "Cruzeiro", pais: 'BR', escudo: 'cruzeiro.svg' },
  { id: 'crystal-palace', nome: "Crystal Palace", pais: 'EN', escudo: 'crystal-palace.png' },
  { id: 'cska-moscow', nome: "CSKA Moscou", pais: 'RU', escudo: 'cska-moscow.png' },
  { id: 'cska-sofia', nome: "CSKA Sofia", pais: 'BG', escudo: 'cska-sofia.png' },
  { id: 'd-c-united', nome: "D.C. United", pais: 'US', escudo: 'd-c-united.svg' },
  { id: 'danubio', nome: "danubio", pais: 'UY', escudo: 'danubio.png' },
  { id: 'darlington-football-club-1883', nome: "Darlington Football Club 1883", pais: 'EN', escudo: 'darlington-football-club-1883.png' },
  { id: 'defensa-y-justicia', nome: "Defensa y Justicia", pais: 'AR', escudo: 'defensa-y-justicia.svg' },
  { id: 'democrata-futebol-clube', nome: "Democrata Futebol Clube", pais: 'BR', escudo: 'democrata-futebol-clube.png' },
  { id: 'deportivo-a-coruna', nome: "Deportivo A Coruña", pais: 'ES', escudo: 'deportivo-a-coruna.png' },
  { id: 'deportivo-maldonado-de-puerto-maldonado', nome: "Deportivo Maldonado de Puerto Maldonado", pais: 'PE', escudo: 'deportivo-maldonado-de-puerto-maldonado.png' },
  { id: 'derby-county-football-club', nome: "Derby County Football Club", pais: 'EN', escudo: 'derby-county-football-club.png' },
  { id: 'drumchapel-amateur-f-c', nome: "Drumchapel Amateur F.C.", pais: 'EN', escudo: 'drumchapel-amateur-f-c.png' },
  { id: 'dundee-united-football-club', nome: "Dundee United Football Club", pais: 'EN', escudo: 'dundee-united-football-club.png' },
  { id: 'dunfermline-athletic-football-club', nome: "Dunfermline Athletic Football Club", pais: 'EN', escudo: 'dunfermline-athletic-football-club.png' },
  { id: 'dusseldorf', nome: "Düsseldorf", pais: 'DE', escudo: 'dusseldorf.svg' },
  { id: 'dynamo-moscow', nome: "Dynamo Moscow", pais: 'RU', escudo: 'dynamo-moscow.png' },
  { id: 'eibar', nome: "Éibar", pais: 'ES', escudo: 'eibar.svg' },
  { id: 'emelec', nome: "emelec", pais: 'EC', escudo: 'emelec.png' },
  { id: 'emirates-club', nome: "Emirates Club", pais: 'AE', escudo: 'emirates-club.png' },
  { id: 'empoli', nome: "Empoli", pais: 'IT', escudo: 'empoli.svg' },
  { id: 'esporte-clube-agua-santa', nome: "Esporte Clube Água Santa", pais: 'BR', escudo: 'esporte-clube-agua-santa.png' },
  { id: 'esporte-clube-juventude', nome: "Esporte Clube Juventude", pais: 'BR', escudo: 'esporte-clube-juventude.png' },
  { id: 'esporte-clube-santo-andre', nome: "Esporte Clube Santo André", pais: 'BR', escudo: 'esporte-clube-santo-andre.png' },
  { id: 'esporte-clube-sao-jose', nome: "Esporte Clube São José", pais: 'BR', escudo: 'esporte-clube-sao-jose.png' },
  { id: 'esporte-clube-xv-de-novembro-jau', nome: "Esporte Clube XV de Novembro (Jaú)", pais: 'BR', escudo: 'esporte-clube-xv-de-novembro-jau.svg' },
  { id: 'estrela-vermelha-de-belgrado', nome: "Estrela Vermelha de Belgrado", pais: 'RS', escudo: 'estrela-vermelha-de-belgrado.svg' },
  { id: 'estudiantes', nome: "Estudiantes", pais: 'AR', escudo: 'estudiantes.svg' },
  { id: 'everton', nome: "Everton", pais: 'EN', escudo: 'everton.png' },
  { id: 'everton-de-vina-del-mar', nome: "Everton de Viña del Mar", pais: 'CL', escudo: 'everton-de-vina-del-mar.png' },
  { id: 'fc-anji-makhachkala', nome: "FC Anji Makhachkala", pais: 'RU', escudo: 'fc-anji-makhachkala.png' },
  { id: 'fc-cincinnati', nome: "FC Cincinnati", pais: 'US', escudo: 'fc-cincinnati.svg' },
  { id: 'fc-groningen', nome: "FC Groningen", pais: 'NL', escudo: 'fc-groningen.png' },
  { id: 'fc-imabari', nome: "FC Imabari", pais: 'JP', escudo: 'fc-imabari.png' },
  { id: 'fc-kairat', nome: "FC Kairat", pais: 'KZ', escudo: 'fc-kairat.png' },
  { id: 'fc-kariya', nome: "FC Kariya", pais: 'JP', escudo: 'fc-kariya.png' },
  { id: 'fc-maruyasu-okazaki', nome: "FC Maruyasu Okazaki", pais: 'JP', escudo: 'fc-maruyasu-okazaki.png' },
  { id: 'fc-metz', nome: "FC Metz", pais: 'FR', escudo: 'fc-metz.svg' },
  { id: 'fc-osaka', nome: "FC Osaka", pais: 'JP', escudo: 'fc-osaka.png' },
  { id: 'fc-ryukyu', nome: "FC Ryukyu", pais: 'JP', escudo: 'fc-ryukyu.png' },
  { id: 'fc-sion', nome: "FC Sion", pais: 'CH', escudo: 'fc-sion.png' },
  { id: 'fc-tokyo', nome: "FC Tokyo", pais: 'JP', escudo: 'fc-tokyo.svg' },
  { id: 'fc-twente-enschede', nome: "FC Twente Enschede", pais: 'NL', escudo: 'fc-twente-enschede.png' },
  { id: 'fc-utrecht', nome: "FC Utrecht", pais: 'NL', escudo: 'fc-utrecht.png' },
  { id: 'fc-volyn-lutsk', nome: "FC Volyn Lutsk", pais: 'UA', escudo: 'fc-volyn-lutsk.png' },
  { id: 'fc-zenit-sao-petersburgo', nome: "FC Zenit São Petersburgo", pais: 'RU', escudo: 'fc-zenit-sao-petersburgo.svg' },
  { id: 'fenerbahce', nome: "Fenerbahçe", pais: 'TR', escudo: 'fenerbahce.png' },
  { id: 'feyenoord', nome: "Feyenoord", pais: 'NL', escudo: 'feyenoord.png' },
  { id: 'figueirense', nome: "Figueirense", pais: 'BR', escudo: 'figueirense.svg' },
  { id: 'fiorentina', nome: "Fiorentina", pais: 'IT', escudo: 'fiorentina.svg' },
  { id: 'fk-cukaricki', nome: "FK Cukaricki", pais: 'RS', escudo: 'fk-cukaricki.png' },
  { id: 'fk-jablonec', nome: "FK Jablonec", pais: 'CZ', escudo: 'fk-jablonec.png' },
  { id: 'fk-partizan-belgrade', nome: "FK Partizan Belgrade", pais: 'RS', escudo: 'fk-partizan-belgrade.png' },
  { id: 'fk-teleoptik', nome: "FK Teleoptik", pais: 'RS', escudo: 'fk-teleoptik.png' },
  { id: 'flamengo', nome: "Flamengo", pais: 'BR', escudo: 'flamengo.svg' },
  { id: 'fleetwood-town-football-club', nome: "Fleetwood Town Football Club", pais: 'EN', escudo: 'fleetwood-town-football-club.png' },
  { id: 'fluminense', nome: "Fluminense", pais: 'BR', escudo: 'fluminense.svg' },
  { id: 'football-club-halifax-town', nome: "Football Club Halifax Town", pais: 'EN', escudo: 'football-club-halifax-town.png' },
  { id: 'fortaleza-esporte-clube', nome: "Fortaleza Esporte Clube", pais: 'BR', escudo: 'fortaleza-esporte-clube.png' },
  { id: 'fortuna-sittard', nome: "Fortuna Sittard", pais: 'NL', escudo: 'fortuna-sittard.png' },
  { id: 'fulham', nome: "Fulham", pais: 'EN', escudo: 'fulham.svg' },
  { id: 'galatasaray', nome: "Galatasaray", pais: 'TR', escudo: 'galatasaray.png' },
  { id: 'gamba-osaka', nome: "Gamba Osaka", pais: 'JP', escudo: 'gamba-osaka.svg' },
  { id: 'genoa', nome: "Genoa", pais: 'IT', escudo: 'genoa.svg' },
  { id: 'getafe', nome: "Getafe", pais: 'ES', escudo: 'getafe.png' },
  { id: 'gijon', nome: "Gijón", pais: 'ES', escudo: 'gijon.svg' },
  { id: 'gil-vicente-fc', nome: "Gil Vicente FC", pais: 'PT', escudo: 'gil-vicente-fc.png' },
  { id: 'girona', nome: "Girona", pais: 'ES', escudo: 'girona.svg' },
  { id: 'gnk-dinamo-zagreb', nome: "GNK Dinamo Zagreb", pais: 'HR', escudo: 'gnk-dinamo-zagreb.png' },
  { id: 'goias', nome: "Goias", pais: 'BR', escudo: 'goias.svg' },
  { id: 'granada', nome: "Granada", pais: 'ES', escudo: 'granada.svg' },
  { id: 'gremio', nome: "Grêmio", pais: 'BR', escudo: 'gremio.svg' },
  { id: 'guarani-futebol-clube', nome: "Guarani Futebol Clube", pais: 'BR', escudo: 'guarani-futebol-clube.svg' },
  { id: 'guaratingueta-futebol-ltda', nome: "Guaratinguetá Futebol Ltda.", pais: 'BR', escudo: 'guaratingueta-futebol-ltda.png' },
  { id: 'hajduk-split', nome: "Hajduk Split", pais: 'HR', escudo: 'hajduk-split.png' },
  { id: 'halmstads-bk', nome: "Halmstads BK", pais: 'SE', escudo: 'halmstads-bk.png' },
  { id: 'hamburgo', nome: "Hamburgo", pais: 'DE', escudo: 'hamburgo.svg' },
  { id: 'hamilton-academical-football-club', nome: "Hamilton Academical Football Club", pais: 'EN', escudo: 'hamilton-academical-football-club.png' },
  { id: 'hangzhou-greentown-football-club', nome: "Hangzhou Greentown Football Club", pais: 'CN', escudo: 'hangzhou-greentown-football-club.png' },
  { id: 'hannover', nome: "Hannover", pais: 'DE', escudo: 'hannover.svg' },
  { id: 'hebei-football-club', nome: "Hebei Football Club", pais: 'CN', escudo: 'hebei-football-club.png' },
  { id: 'hertha', nome: "Hertha", pais: 'DE', escudo: 'hertha.svg' },
  { id: 'hoffenheim', nome: "Hoffenheim", pais: 'DE', escudo: 'hoffenheim.svg' },
  { id: 'honda-fc', nome: "Honda FC", pais: 'JP', escudo: 'honda-fc.png' },
  { id: 'hotspur', nome: "Hotspur", pais: 'EN', escudo: 'hotspur.svg' },
  { id: 'houston-dynamo', nome: "Houston Dynamo", pais: 'US', escudo: 'houston-dynamo.svg' },
  { id: 'huddersfield-town-football-club', nome: "Huddersfield Town Football Club", pais: 'EN', escudo: 'huddersfield-town-football-club.png' },
  { id: 'hull-city', nome: "Hull City", pais: 'EN', escudo: 'hull-city.png' },
  { id: 'if-brommapojkarna', nome: "IF Brommapojkarna", pais: 'SE', escudo: 'if-brommapojkarna.png' },
  { id: 'independiente', nome: "Independiente", pais: 'AR', escudo: 'independiente.svg' },
  { id: 'independiente-santa-fe-femenino', nome: "Independiente Santa Fe Femenino", pais: 'CO', escudo: 'independiente-santa-fe-femenino.png' },
  { id: 'inter', nome: "Inter de Milão", pais: 'IT', escudo: 'inter.png' },
  { id: 'inter-miami', nome: "Inter Miami", pais: 'US', escudo: 'inter-miami.svg' },
  { id: 'internacional', nome: "Internacional", pais: 'BR', escudo: 'internacional.svg' },
  { id: 'ipswich', nome: "Ipswich", pais: 'EN', escudo: 'ipswich.png' },
  { id: 'istanbul-buyuksehir-belediyespor', nome: "İstanbul Büyükşehir Belediyespor", pais: 'TR', escudo: 'istanbul-buyuksehir-belediyespor.png' },
  { id: 'ituano-futebol-clube', nome: "Ituano Futebol Clube", pais: 'BR', escudo: 'ituano-futebol-clube.png' },
  { id: 'itumbiara-esporte-clube', nome: "Itumbiara Esporte Clube", pais: 'BR', escudo: 'itumbiara-esporte-clube.png' },
  { id: 'jamshedpur-fc', nome: "Jamshedpur FC", pais: 'IN', escudo: 'jamshedpur-fc.png' },
  { id: 'jef-united-chiba', nome: "JEF United Chiba", pais: 'JP', escudo: 'jef-united-chiba.svg' },
  { id: 'jeonbuk-hyundai', nome: "Jeonbuk Hyundai", pais: 'KR', escudo: 'jeonbuk-hyundai.svg' },
  { id: 'joinville', nome: "Joinville", pais: 'BR', escudo: 'joinville.png' },
  { id: 'jubiro-iwata', nome: "Jubiro Iwata", pais: 'JP', escudo: 'jubiro-iwata.png' },
  { id: 'juventus', nome: "Juventus", pais: 'IT', escudo: 'juventus.svg' },
  { id: 'kaa-gent', nome: "KAA Gent", pais: 'BE', escudo: 'kaa-gent.png' },
  { id: 'karlsruher', nome: "Karlsruher", pais: 'DE', escudo: 'karlsruher.svg' },
  { id: 'kashima-antlers', nome: "Kashima Antlers", pais: 'JP', escudo: 'kashima-antlers.svg' },
  { id: 'kashiwa-reysol', nome: "Kashiwa Reysol", pais: 'JP', escudo: 'kashiwa-reysol.png' },
  { id: 'kawasaki-frontale', nome: "Kawasaki Frontale", pais: 'JP', escudo: 'kawasaki-frontale.png' },
  { id: 'kayserispor', nome: "Kayserispor", pais: 'TR', escudo: 'kayserispor.png' },
  { id: 'kerala-blaster-football-club', nome: "Kerala Blaster Football Club", pais: 'IN', escudo: 'kerala-blaster-football-club.png' },
  { id: 'konyaspor', nome: "Konyaspor", pais: 'TR', escudo: 'konyaspor.png' },
  { id: 'la-galaxy', nome: "LA Galaxy", pais: 'US', escudo: 'la-galaxy.svg' },
  { id: 'lazio', nome: "Lazio", pais: 'IT', escudo: 'lazio.svg' },
  { id: 'ld-alajuelense', nome: "LD Alajuelense", pais: 'CR', escudo: 'ld-alajuelense.svg' },
  { id: 'leeds-united', nome: "Leeds United", pais: 'EN', escudo: 'leeds-united.svg' },
  { id: 'leicester', nome: "Leicester", pais: 'EN', escudo: 'leicester.png' },
  { id: 'lens', nome: "Lens", pais: 'FR', escudo: 'lens.png' },
  { id: 'leyton-orient-football-club', nome: "Leyton Orient Football Club", pais: 'EN', escudo: 'leyton-orient-football-club.png' },
  { id: 'libertad', nome: "libertad", pais: 'PY', escudo: 'libertad.png' },
  { id: 'liverpool', nome: "Liverpool", pais: 'EN', escudo: 'liverpool.svg' },
  { id: 'liverpool-futbol-club', nome: "Liverpool Fútbol Club", pais: 'UY', escudo: 'liverpool-futbol-club.png' },
  { id: 'lokomotiv-moscow', nome: "Lokomotiv Moscou", pais: 'RU', escudo: 'lokomotiv-moscow.png' },
  { id: 'los-angeles-aztecs', nome: "Los Angeles Aztecs", pais: 'US', escudo: 'los-angeles-aztecs.png' },
  { id: 'los-angeles-football-club', nome: "Los Angeles Football Club", pais: 'US', escudo: 'los-angeles-football-club.svg' },
  { id: 'luton-town', nome: "Luton Town", pais: 'EN', escudo: 'luton-town.png' },
  { id: 'machida-zelvia', nome: "Machida Zelvia", pais: 'JP', escudo: 'machida-zelvia.svg' },
  { id: 'madureira-esporte-clube', nome: "Madureira Esporte Clube", pais: 'BR', escudo: 'madureira-esporte-clube.svg' },
  { id: 'malaga', nome: "Malaga", pais: 'ES', escudo: 'malaga.png' },
  { id: 'mallorca', nome: "Mallorca", pais: 'ES', escudo: 'mallorca.png' },
  { id: 'man-city', nome: "Man City", pais: 'EN', escudo: 'man-city.png' },
  { id: 'manchester-city', nome: "Manchester City", pais: 'EN', escudo: 'manchester-city.png' },
  { id: 'manchester-united', nome: "Manchester United", pais: 'EN', escudo: 'manchester-united.png' },
  { id: 'melbourne-city-football-club', nome: "Melbourne City Football Club", pais: 'AU', escudo: 'melbourne-city-football-club.png' },
  { id: 'milan', nome: "Milan", pais: 'IT', escudo: 'milan.svg' },
  { id: 'millonarios', nome: "millonarios", pais: 'CO', escudo: 'millonarios.png' },
  { id: 'millwall-football-club', nome: "Millwall Football Club", pais: 'EN', escudo: 'millwall-football-club.png' },
  { id: 'milton-keynes-dons-football-club', nome: "Milton Keynes Dons Football Club", pais: 'EN', escudo: 'milton-keynes-dons-football-club.png' },
  { id: 'mito-hollyhock', nome: "Mito Hollyhock", pais: 'JP', escudo: 'mito-hollyhock.png' },
  { id: 'modena-football-club', nome: "Modena Football Club", pais: 'IT', escudo: 'modena-football-club.png' },
  { id: 'monaco', nome: "Monaco", pais: 'FR', escudo: 'monaco.svg' },
  { id: 'montevideo-wanderers-futbol-club', nome: "Montevideo Wanderers Fútbol Club", pais: 'UY', escudo: 'montevideo-wanderers-futbol-club.png' },
  { id: 'monza', nome: "Monza", pais: 'IT', escudo: 'monza.svg' },
  { id: 'mumbai-city-football-club', nome: "Mumbai City Football Club", pais: 'IN', escudo: 'mumbai-city-football-club.png' },
  { id: 'nacional', nome: "nacional", pais: 'UY', escudo: 'nacional.png' },
  { id: 'nagoya-grampus', nome: "Nagoya Grampus", pais: 'JP', escudo: 'nagoya-grampus.svg' },
  { id: 'nantes', nome: "Nantes", pais: 'FR', escudo: 'nantes.svg' },
  { id: 'napoli', nome: "Napoli", pais: 'IT', escudo: 'napoli.svg' },
  { id: 'nautico', nome: "Nautico", pais: 'BR', escudo: 'nautico.svg' },
  { id: 'newcastle', nome: "Newcastle", pais: 'EN', escudo: 'newcastle.png' },
  { id: 'newcastle-united-jets-football-club', nome: "Newcastle United Jets Football Club", pais: 'AU', escudo: 'newcastle-united-jets-football-club.png' },
  { id: 'newell-s', nome: "Newell's", pais: 'AR', escudo: 'newell-s.svg' },
  { id: 'newport-county-association-football-club', nome: "Newport County Association Football Club", pais: 'EN', escudo: 'newport-county-association-football-club.png' },
  { id: 'nice', nome: "Nice", pais: 'FR', escudo: 'nice.png' },
  { id: 'nk-hrvatski-dragovoljac', nome: "NK Hrvatski Dragovoljac", pais: 'HR', escudo: 'nk-hrvatski-dragovoljac.png' },
  { id: 'nk-inter-zapresic', nome: "NK Inter Zaprešić", pais: 'HR', escudo: 'nk-inter-zapresic.png' },
  { id: 'nk-lokomotiva-zagreb', nome: "NK Lokomotiva Zagreb", pais: 'HR', escudo: 'nk-lokomotiva-zagreb.png' },
  { id: 'nk-zadar', nome: "NK Zadar", pais: 'HR', escudo: 'nk-zadar.png' },
  { id: 'norwich', nome: "Norwich", pais: 'EN', escudo: 'norwich.png' },
  { id: 'nottingham', nome: "Nottingham", pais: 'EN', escudo: 'nottingham.svg' },
  { id: 'notts-county-football-club', nome: "Notts County Football Club", pais: 'EN', escudo: 'notts-county-football-club.png' },
  { id: 'odisha-fc', nome: "Odisha FC", pais: 'IN', escudo: 'odisha-fc.png' },
  { id: 'oita-trinita', nome: "Oita Trinita", pais: 'JP', escudo: 'oita-trinita.svg' },
  { id: 'olaria-atletico-clube', nome: "Olaria Atlético Clube", pais: 'BR', escudo: 'olaria-atletico-clube.png' },
  { id: 'olympiacos-piraeus', nome: "Olympiacos Piraeus", pais: 'GR', escudo: 'olympiacos-piraeus.png' },
  { id: 'olympique-lyon', nome: "Olympique Lyon", pais: 'FR', escudo: 'olympique-lyon.png' },
  { id: 'omladinski-fudbalski-klub-beograd', nome: "Omladinski Fudbalski Klub Beograd", pais: 'RS', escudo: 'omladinski-fudbalski-klub-beograd.png' },
  { id: 'operario-ferroviario-esporte-clube', nome: "Operário Ferroviário Esporte Clube", pais: 'BR', escudo: 'operario-ferroviario-esporte-clube.png' },
  { id: 'orlando-city', nome: "Orlando City", pais: 'US', escudo: 'orlando-city.svg' },
  { id: 'osasuna', nome: "Osasuna", pais: 'ES', escudo: 'osasuna.svg' },
  { id: 'oxford-united-football-club', nome: "Oxford United Football Club", pais: 'EN', escudo: 'oxford-united-football-club.png' },
  { id: 'palermo-football-club', nome: "Palermo Football Club", pais: 'IT', escudo: 'palermo-football-club.png' },
  { id: 'palmeiras', nome: "Palmeiras", pais: 'BR', escudo: 'palmeiras.svg' },
  { id: 'panathinaikos', nome: "Panathinaikos", pais: 'GR', escudo: 'panathinaikos.png' },
  { id: 'paok-thessaloniki', nome: "PAOK Thessaloniki", pais: 'GR', escudo: 'paok-thessaloniki.png' },
  { id: 'parma', nome: "Parma", pais: 'IT', escudo: 'parma.svg' },
  { id: 'paulinia-futebol-clube', nome: "Paulínia Futebol Clube", pais: 'BR', escudo: 'paulinia-futebol-clube.png' },
  { id: 'penarol', nome: "penarol", pais: 'UY', escudo: 'penarol.png' },
  { id: 'perugia-calcio', nome: "Perugia Calcio", pais: 'IT', escudo: 'perugia-calcio.png' },
  { id: 'pescara-calcio', nome: "Pescara Calcio", pais: 'IT', escudo: 'pescara-calcio.png' },
  { id: 'peterborough-united-football-club', nome: "Peterborough United Football Club", pais: 'EN', escudo: 'peterborough-united-football-club.png' },
  { id: 'piacenza-calcio', nome: "Piacenza Calcio", pais: 'IT', escudo: 'piacenza-calcio.png' },
  { id: 'pisa', nome: "Pisa", pais: 'IT', escudo: 'pisa.svg' },
  { id: 'ponte-preta', nome: "Ponte Preta", pais: 'BR', escudo: 'ponte-preta.svg' },
  { id: 'portimonense', nome: "Portimonense", pais: 'PT', escudo: 'portimonense.png' },
  { id: 'porto', nome: "Porto", pais: 'PT', escudo: 'porto.png' },
  { id: 'portsmouth-football-club', nome: "Portsmouth Football Club", pais: 'EN', escudo: 'portsmouth-football-club.png' },
  { id: 'portuguesa', nome: "Portuguesa", pais: 'BR', escudo: 'portuguesa.png' },
  { id: 'preston-north-end-football-club', nome: "Preston North End Football Club", pais: 'EN', escudo: 'preston-north-end-football-club.png' },
  { id: 'psv', nome: "PSV", pais: 'NL', escudo: 'psv.png' },
  { id: 'queen-s-park-football-club', nome: "Queen's Park Football Club", pais: 'EN', escudo: 'queen-s-park-football-club.png' },
  { id: 'rangers-football-club', nome: "Rangers Football Club", pais: 'EN', escudo: 'rangers-football-club.png' },
  { id: 'reading', nome: "Reading", pais: 'EN', escudo: 'reading.png' },
  { id: 'real-betis', nome: "Real Betis", pais: 'ES', escudo: 'real-betis.svg' },
  { id: 'real-madrid', nome: "Real Madrid", pais: 'ES', escudo: 'real-madrid.png' },
  { id: 'red-bull-new-york', nome: "Red Bull New York", pais: 'US', escudo: 'red-bull-new-york.svg' },
  { id: 'renofa-yamaguchi', nome: "Renofa Yamaguchi", pais: 'JP', escudo: 'renofa-yamaguchi.svg' },
  { id: 'rio-ave-fc', nome: "Rio Ave FC", pais: 'PT', escudo: 'rio-ave-fc.png' },
  { id: 'rio-claro-futebol-clube', nome: "Rio Claro Futebol Clube", pais: 'BR', escudo: 'rio-claro-futebol-clube.svg' },
  { id: 'rio-preto-esporte-clube', nome: "Rio Preto Esporte Clube", pais: 'BR', escudo: 'rio-preto-esporte-clube.png' },
  { id: 'river-plate', nome: "River Plate", pais: 'AR', escudo: 'river-plate.svg' },
  { id: 'rkc-waalwijk', nome: "RKC Waalwijk", pais: 'NL', escudo: 'rkc-waalwijk.png' },
  { id: 'roma', nome: "Roma", pais: 'IT', escudo: 'roma.png' },
  { id: 'rosario-central', nome: "Rosario Central", pais: 'AR', escudo: 'rosario-central.svg' },
  { id: 'rotherham-united-football-club', nome: "Rotherham United Football Club", pais: 'EN', escudo: 'rotherham-united-football-club.png' },
  { id: 'rsc-anderlecht', nome: "RSC Anderlecht", pais: 'BE', escudo: 'rsc-anderlecht.png' },
  { id: 'samsunspor', nome: "Samsunspor", pais: 'TR', escudo: 'samsunspor.png' },
  { id: 'sanfrecce-hiroshima', nome: "Sanfrecce Hiroshima", pais: 'JP', escudo: 'sanfrecce-hiroshima.png' },
  { id: 'santander', nome: "Santander", pais: 'ES', escudo: 'santander.svg' },
  { id: 'santos', nome: "Santos", pais: 'BR', escudo: 'santos.svg' },
  { id: 'sao-bernardo-futebol-clube', nome: "São Bernardo Futebol Clube", pais: 'BR', escudo: 'sao-bernardo-futebol-clube.png' },
  { id: 'sao-paulo', nome: "São Paulo", pais: 'BR', escudo: 'sao-paulo.svg' },
  { id: 'sarmiento', nome: "Sarmiento", pais: 'AR', escudo: 'sarmiento.svg' },
  { id: 'sassuolo', nome: "Sassuolo", pais: 'IT', escudo: 'sassuolo.svg' },
  { id: 'sc-braga', nome: "SC Braga", pais: 'PT', escudo: 'sc-braga.png' },
  { id: 'schalke', nome: "Schalke 04", pais: 'DE', escudo: 'schalke.svg' },
  { id: 'seattle-sounders', nome: "Seattle Sounders", pais: 'US', escudo: 'seattle-sounders.svg' },
  { id: 'servette-fc', nome: "Servette FC", pais: 'CH', escudo: 'servette-fc.png' },
  { id: 'sevilla', nome: "Sevilla", pais: 'ES', escudo: 'sevilla.png' },
  { id: 'shakhtar', nome: "Shakhtar Donetsk", pais: 'UA', escudo: 'shakhtar.png' },
  { id: 'shandong-luneng', nome: "Shandong Taishan", pais: 'CN', escudo: 'shandong-luneng.png' },
  { id: 'shanghai-shenhua', nome: "Shanghai Shenhua", pais: 'CN', escudo: 'shanghai-shenhua.png' },
  { id: 'shanghai-sipg', nome: "Shanghai Port", pais: 'CN', escudo: 'shanghai-sipg.png' },
  { id: 'sharjah-fc', nome: "Sharjah FC", pais: 'AE', escudo: 'sharjah-fc.png' },
  { id: 'sheffield-wednesday', nome: "Sheffield Wednesday", pais: 'EN', escudo: 'sheffield-wednesday.png' },
  { id: 'shimizu-s-pulse', nome: "Shimizu S-Pulse", pais: 'JP', escudo: 'shimizu-s-pulse.svg' },
  { id: 'shonan-bellmare', nome: "Shonan Bellmare", pais: 'JP', escudo: 'shonan-bellmare.svg' },
  { id: 'shrewsbury-town-football-club', nome: "Shrewsbury Town Football Club", pais: 'EN', escudo: 'shrewsbury-town-football-club.png' },
  { id: 'siracusa-calcio-1924', nome: "Siracusa Calcio 1924", pais: 'IT', escudo: 'siracusa-calcio-1924.png' },
  { id: 'sk-sigma-olomouc', nome: "SK Sigma Olomouc", pais: 'CZ', escudo: 'sk-sigma-olomouc.png' },
  { id: 'sociedade-desportiva-juazeirense', nome: "Sociedade Desportiva Juazeirense", pais: 'BR', escudo: 'sociedade-desportiva-juazeirense.png' },
  { id: 'societa-polisportiva-ars-et-labor-1907', nome: "Società Polisportiva Ars et Labor 1907", pais: 'IT', escudo: 'societa-polisportiva-ars-et-labor-1907.svg' },
  { id: 'southampton', nome: "Southampton", pais: 'EN', escudo: 'southampton.png' },
  { id: 'spartak', nome: "Spartak", pais: 'RS', escudo: 'spartak.png' },
  { id: 'spartak-moscow', nome: "Spartak Moscow", pais: 'RU', escudo: 'spartak-moscow.png' },
  { id: 'sport', nome: "Sport Recife", pais: 'BR', escudo: 'sport.png' },
  { id: 'sport-boys-association', nome: "Sport Boys Association", pais: 'PE', escudo: 'sport-boys-association.svg' },
  { id: 'sporting-cp', nome: "Sporting", pais: 'PT', escudo: 'sporting-cp.png' },
  { id: 'st-pauli', nome: "St. Pauli", pais: 'DE', escudo: 'st-pauli.png' },
  { id: 'standard-liege', nome: "Standard Liège", pais: 'BE', escudo: 'standard-liege.png' },
  { id: 'stella-foot-ball-club', nome: "Stella Foot-Ball Club", pais: 'BR', escudo: 'stella-foot-ball-club.png' },
  { id: 'stocksbridge-park-steels-f-c', nome: "Stocksbridge Park Steels F.C.", pais: 'EN', escudo: 'stocksbridge-park-steels-f-c.png' },
  { id: 'stoke-city-football-club', nome: "Stoke City Football Club", pais: 'EN', escudo: 'stoke-city-football-club.png' },
  { id: 'stuttgart', nome: "Stuttgart", pais: 'DE', escudo: 'stuttgart.svg' },
  { id: 'sunderland', nome: "Sunderland", pais: 'EN', escudo: 'sunderland.svg' },
  { id: 'swansea-city-association-football-club', nome: "Swansea City Association Football Club", pais: 'EN', escudo: 'swansea-city-association-football-club.png' },
  { id: 'swindon-town-football-club', nome: "Swindon Town Football Club", pais: 'EN', escudo: 'swindon-town-football-club.png' },
  { id: 'sydney-football-club', nome: "Sydney Football Club", pais: 'AU', escudo: 'sydney-football-club.png' },
  { id: 'sydney-united-58-football-club', nome: "Sydney United 58 Football Club", pais: 'AU', escudo: 'sydney-united-58-football-club.png' },
  { id: 'takushoku-university-association-football-club', nome: "Takushoku University Association Football Club", pais: 'JP', escudo: 'takushoku-university-association-football-club.png' },
  { id: 'talleres', nome: "Talleres", pais: 'AR', escudo: 'talleres.svg' },
  { id: 'tegevajaro-miyazaki', nome: "Tegevajaro Miyazaki", pais: 'JP', escudo: 'tegevajaro-miyazaki.png' },
  { id: 'tianjin-tianhai-football-club', nome: "Tianjin Tianhai Football Club", pais: 'CN', escudo: 'tianjin-tianhai-football-club.png' },
  { id: 'tigres', nome: "tigres", pais: 'MX', escudo: 'tigres.png' },
  { id: 'tokushima-vortis', nome: "Tokushima Vortis", pais: 'JP', escudo: 'tokushima-vortis.svg' },
  { id: 'tokyo-verdy', nome: "Tokyo Verdy", pais: 'JP', escudo: 'tokyo-verdy.svg' },
  { id: 'tombense-futebol-clube', nome: "Tombense Futebol Clube", pais: 'BR', escudo: 'tombense-futebol-clube.svg' },
  { id: 'torino', nome: "Torino", pais: 'IT', escudo: 'torino.svg' },
  { id: 'toulouse', nome: "Toulouse", pais: 'FR', escudo: 'toulouse.png' },
  { id: 'trabzonspor', nome: "Trabzonspor", pais: 'TR', escudo: 'trabzonspor.png' },
  { id: 'u-s-livorno-1915', nome: "U.S. Livorno 1915", pais: 'IT', escudo: 'u-s-livorno-1915.png' },
  { id: 'uberlandia-esporte-clube', nome: "Uberlândia Esporte Clube", pais: 'BR', escudo: 'uberlandia-esporte-clube.png' },
  { id: 'udinese', nome: "Udinese", pais: 'IT', escudo: 'udinese.png' },
  { id: 'uniao-sao-joao-esporte-clube', nome: "União São João Esporte Clube", pais: 'BR', escudo: 'uniao-sao-joao-esporte-clube.png' },
  { id: 'unione-sportiva-avellino-1912', nome: "Unione Sportiva Avellino 1912", pais: 'IT', escudo: 'unione-sportiva-avellino-1912.png' },
  { id: 'unione-sportiva-catanzaro', nome: "Unione Sportiva Catanzaro", pais: 'IT', escudo: 'unione-sportiva-catanzaro.png' },
  { id: 'united-football-club', nome: "United Football Club", pais: 'AE', escudo: 'united-football-club.svg' },
  { id: 'urawa-red-diamonds', nome: "Urawa Red Diamonds", pais: 'JP', escudo: 'urawa-red-diamonds.png' },
  { id: 'us-salernitana-1919', nome: "US Salernitana 1919", pais: 'IT', escudo: 'us-salernitana-1919.png' },
  { id: 'v-varen-nagasaki', nome: "V-Varen Nagasaki", pais: 'JP', escudo: 'v-varen-nagasaki.svg' },
  { id: 'valencia', nome: "Valencia", pais: 'ES', escudo: 'valencia.svg' },
  { id: 'vallecano', nome: "Vallecano", pais: 'ES', escudo: 'vallecano.png' },
  { id: 'vancouver-whitecaps-q196107', nome: "Vancouver Whitecaps", pais: 'CA', escudo: 'vancouver-whitecaps-q196107.png' },
  { id: 'vasco', nome: "Vasco da Gama", pais: 'BR', escudo: 'vasco.svg' },
  { id: 'velez-sarsfield', nome: "Vélez Sarsfield", pais: 'AR', escudo: 'velez-sarsfield.svg' },
  { id: 'vestel-manisaspor', nome: "Vestel Manisaspor", pais: 'TR', escudo: 'vestel-manisaspor.png' },
  { id: 'vila-nova', nome: "Vila Nova", pais: 'BR', escudo: 'vila-nova.svg' },
  { id: 'villarreal', nome: "Villarreal", pais: 'ES', escudo: 'villarreal.svg' },
  { id: 'vissel-kobe', nome: "Vissel Kobe", pais: 'JP', escudo: 'vissel-kobe.svg' },
  { id: 'vit-guimaraes', nome: "Vit. Guimarães", pais: 'PT', escudo: 'vit-guimaraes.png' },
  { id: 'vitoria', nome: "Vitória", pais: 'BR', escudo: 'vitoria.svg' },
  { id: 'vonds-ichihara', nome: "Vonds Ichihara", pais: 'JP', escudo: 'vonds-ichihara.png' },
  { id: 'watford-fc', nome: "Watford FC", pais: 'EN', escudo: 'watford-fc.png' },
  { id: 'werder-bremen', nome: "Werder Bremen", pais: 'DE', escudo: 'werder-bremen.png' },
  { id: 'west-bromwich-albion-football-club', nome: "West Bromwich Albion Football Club", pais: 'EN', escudo: 'west-bromwich-albion-football-club.png' },
  { id: 'west-ham', nome: "West Ham", pais: 'EN', escudo: 'west-ham.svg' },
  { id: 'western-sydney-wanderers-football-club', nome: "Western Sydney Wanderers Football Club", pais: 'AU', escudo: 'western-sydney-wanderers-football-club.png' },
  { id: 'western-united', nome: "Western United", pais: 'EN', escudo: 'western-united.svg' },
  { id: 'widzew-lodz', nome: "Widzew Lodz", pais: 'PL', escudo: 'widzew-lodz.png' },
  { id: 'wigan-athletic-football-club', nome: "Wigan Athletic Football Club", pais: 'EN', escudo: 'wigan-athletic-football-club.png' },
  { id: 'willem-ii', nome: "Willem II", pais: 'NL', escudo: 'willem-ii.png' },
  { id: 'wisla-krakow', nome: "Wisla Kraków", pais: 'PL', escudo: 'wisla-krakow.png' },
  { id: 'wolfsburg', nome: "Wolfsburg", pais: 'DE', escudo: 'wolfsburg.svg' },
  { id: 'wolverhampton-wanderers', nome: "Wolverhampton Wanderers", pais: 'EN', escudo: 'wolverhampton-wanderers.png' },
  { id: 'wuhan-three-towns-football-club', nome: "Wuhan Three Towns Football Club", pais: 'CN', escudo: 'wuhan-three-towns-football-club.png' },
  { id: 'yokohama-fc', nome: "Yokohama FC", pais: 'JP', escudo: 'yokohama-fc.png' },
  { id: 'yokohama-marinos', nome: "Yokohama Marinos", pais: 'JP', escudo: 'yokohama-marinos.png' },
  { id: 'zaragoza', nome: "Zaragoza", pais: 'ES', escudo: 'zaragoza.png' },
]

export const CLUBE_POR_ID = new Map(CLUBES.map((c) => [c.id, c]))
