import type { Jogador } from './tipos'

/**
 * Onda 1 da biblioteca — 15 jogadores por nível.
 *
 * Convenções:
 * - `clubes` lista só clubes de futebol profissional adulto, em ordem
 *   cronológica, sem repetir um clube ao qual o jogador voltou.
 * - `dica` revela um fato marcante sem citar nome, clube, posição ou ano.
 * - `apelidos` não precisa cobrir acentuação nem caixa: a comparação normaliza.
 * - `verificado: true` marca a carreira conferida contra fonte externa.
 *
 * ATENÇÃO: nenhuma carreira desta onda foi conferida contra fonte externa — o
 * ambiente não alcança Ogol, Transfermarkt nem Wikipédia. Os erros já
 * encontrados (Džeko sem o início na Bósnia e na Tchéquia, Keirrison sem a
 * volta ao Coritiba) indicam que outros devem existir. Rodar
 * scripts/verificar-carreiras.mjs antes de confiar nesta lista.
 */
export const JOGADORES: Jogador[] = [
  // ==================================================================
  // FÁCIL — reconhecimento imediato, carreira curta e icônica
  // ==================================================================
  {
    id: 'messi',
    nome: 'Lionel Messi',
    apelidos: ['messi', 'leo messi', 'lionel andres messi'],
    nivel: 'facil',
    clubes: ['barcelona', 'psg', 'inter-miami'],
    dica: 'Ganhou o prêmio de melhor do mundo mais vezes que qualquer outro, mas só levantou a maior taça de todas na última tentativa.',
  },
  {
    id: 'cristiano-ronaldo',
    nome: 'Cristiano Ronaldo',
    apelidos: ['cristiano', 'cr7', 'cristiano ronaldo dos santos aveiro'],
    nivel: 'facil',
    clubes: ['sporting-cp', 'manchester-united', 'real-madrid', 'juventus', 'al-nassr'],
    dica: 'Nenhum homem marcou mais gols por uma seleção nacional do que ele.',
  },
  {
    id: 'neymar',
    nome: 'Neymar',
    apelidos: ['neymar jr', 'neymar junior', 'ney'],
    nivel: 'facil',
    clubes: ['santos', 'barcelona', 'psg', 'al-hilal'],
    dica: 'A transferência que o tirou da Espanha continua sendo a mais cara já paga por um jogador.',
  },
  {
    id: 'ronaldinho',
    nome: 'Ronaldinho Gaúcho',
    apelidos: ['ronaldinho', 'ronaldo de assis moreira', 'dinho'],
    nivel: 'facil',
    clubes: ['gremio', 'psg', 'barcelona', 'milan', 'flamengo', 'atletico-mg'],
    dica: 'Uma falta cobrada de muito longe, num estádio inglês em 2002, tirou um goleiro do lugar e um país da Copa.',
  },
  {
    id: 'kaka',
    nome: 'Kaká',
    apelidos: ['kaka', 'ricardo kaka', 'ricardo izecson'],
    nivel: 'facil',
    clubes: ['sao-paulo', 'milan', 'real-madrid', 'orlando-city'],
    dica: 'Foi o último a interromper o duopólio que dominou o prêmio de melhor do mundo por mais de uma década.',
  },
  {
    id: 'ronaldo-fenomeno',
    nome: 'Ronaldo Fenômeno',
    apelidos: ['ronaldo', 'ronaldo fenomeno', 'ronaldo nazario', 'r9', 'ronaldo luis nazario de lima'],
    nivel: 'facil',
    clubes: ['cruzeiro', 'psv', 'barcelona', 'inter', 'real-madrid', 'milan', 'corinthians'],
    dica: 'Voltou de duas cirurgias no mesmo joelho para ser artilheiro de uma Copa do Mundo e calar quem o dava como acabado.',
  },
  {
    id: 'zidane',
    nome: 'Zinedine Zidane',
    apelidos: ['zidane', 'zizou'],
    nivel: 'facil',
    clubes: ['bordeaux', 'juventus', 'real-madrid'],
    dica: 'Sua última partida como profissional terminou numa expulsão que o mundo inteiro reviu em câmera lenta.',
  },
  {
    id: 'ibrahimovic',
    nome: 'Zlatan Ibrahimović',
    apelidos: ['ibrahimovic', 'zlatan', 'ibra'],
    nivel: 'facil',
    clubes: ['ajax', 'juventus', 'inter', 'barcelona', 'milan', 'psg', 'manchester-united', 'la-galaxy'],
    dica: 'Fala de si mesmo na terceira pessoa e marcou de bicicleta de mais de trinta metros.',
  },
  {
    id: 'beckham',
    nome: 'David Beckham',
    apelidos: ['beckham', 'david robert joseph beckham'],
    nivel: 'facil',
    clubes: ['manchester-united', 'real-madrid', 'la-galaxy', 'milan', 'psg'],
    dica: 'Foi expulso numa Copa e virou vilão nacional; anos depois, uma falta nos acréscimos devolveu o país ao Mundial.',
  },
  {
    id: 'drogba',
    nome: 'Didier Drogba',
    apelidos: ['drogba', 'didier yves drogba tebily'],
    nivel: 'facil',
    clubes: ['marseille', 'chelsea', 'shanghai-shenhua', 'galatasaray'],
    dica: 'Dizem que um apelo dele pela televisão ajudou a interromper a guerra civil no seu país.',
  },
  {
    id: 'salah',
    nome: 'Mohamed Salah',
    apelidos: ['salah', 'mo salah', 'mohamed salah hamed mahrous ghaly'],
    nivel: 'facil',
    clubes: ['basel', 'chelsea', 'fiorentina', 'roma', 'liverpool'],
    dica: 'Saiu chorando de campo numa final de Champions por causa do ombro, e voltou para ganhar a seguinte.',
  },
  {
    id: 'casemiro',
    nome: 'Casemiro',
    apelidos: ['casemiro', 'carlos henrique casimiro', 'case'],
    nivel: 'facil',
    clubes: ['sao-paulo', 'real-madrid', 'porto', 'manchester-united'],
    dica: 'Foi o equilíbrio silencioso de um trio de meio-campo que ganhou a Champions três vezes seguidas.',
  },
  {
    id: 'alisson',
    nome: 'Alisson Becker',
    apelidos: ['alisson', 'alisson becker', 'ali'],
    nivel: 'facil',
    clubes: ['internacional', 'roma', 'liverpool'],
    dica: 'Subiu para o ataque no último minuto e marcou de cabeça o gol que garantiu a vaga na Champions.',
  },
  {
    id: 'marcelo',
    nome: 'Marcelo',
    apelidos: ['marcelo', 'marcelo vieira', 'marcelo vieira da silva junior'],
    nivel: 'facil',
    clubes: ['fluminense', 'real-madrid', 'olympiacos'],
    dica: 'É o jogador mais condecorado da história do clube mais vitorioso da Europa.',
  },
  {
    id: 'gabigol',
    nome: 'Gabigol',
    apelidos: ['gabigol', 'gabriel barbosa', 'gabriel barbosa almeida'],
    nivel: 'facil',
    clubes: ['santos', 'inter', 'benfica', 'flamengo', 'cruzeiro'],
    dica: 'Dois gols em três minutos, numa tarde em Lima, viraram uma final continental de cabeça para baixo.',
  },

  // ==================================================================
  // INTERMEDIÁRIO — você conhece, mas precisa pensar
  // ==================================================================
  {
    id: 'ze-roberto',
    nome: 'Zé Roberto',
    apelidos: ['ze roberto', 'jose roberto da silva junior'],
    nivel: 'intermediario',
    clubes: ['portuguesa', 'real-madrid', 'flamengo', 'bayer-leverkusen', 'bayern', 'santos', 'hamburgo', 'palmeiras'],
    dica: 'Seguiu jogando em alto nível depois dos quarenta anos, com um preparo físico que virou lenda entre os companheiros.',
  },
  {
    id: 'juninho-pernambucano',
    nome: 'Juninho Pernambucano',
    apelidos: ['juninho pernambucano', 'juninho', 'antonio augusto ribeiro reis junior'],
    nivel: 'intermediario',
    clubes: ['sport', 'vasco', 'lyon', 'al-gharafa', 'new-york-red-bulls'],
    dica: 'Reinventou a cobrança de falta com um chute sem efeito que despencava no último instante.',
  },
  {
    id: 'sonny-anderson',
    nome: 'Sonny Anderson',
    apelidos: ['sonny anderson', 'sonny anderson da silva'],
    nivel: 'intermediario',
    clubes: ['vasco', 'marseille', 'monaco', 'barcelona', 'lyon', 'villarreal'],
    dica: 'Foi artilheiro do Campeonato Francês por clubes diferentes e, mesmo assim, nunca foi convocado pela sua seleção.',
  },
  {
    id: 'diego-ribas',
    nome: 'Diego Ribas',
    apelidos: ['diego ribas', 'diego', 'diego ribas da cunha'],
    nivel: 'intermediario',
    clubes: ['santos', 'porto', 'werder-bremen', 'juventus', 'wolfsburg', 'atletico-madrid', 'fenerbahce', 'flamengo'],
    dica: 'Camisa 10 clássico, foi eleito o melhor do Campeonato Alemão pouco antes de uma passagem apagada pela Itália.',
  },
  {
    id: 'lucas-moura',
    nome: 'Lucas Moura',
    apelidos: ['lucas moura', 'lucas rodrigues moura da silva'],
    nivel: 'intermediario',
    clubes: ['sao-paulo', 'psg', 'tottenham'],
    dica: 'Marcou três gols numa semifinal de Champions fora de casa e levou o clube a uma final que ninguém esperava.',
  },
  {
    id: 'arturo-vidal',
    nome: 'Arturo Vidal',
    apelidos: ['vidal', 'arturo vidal', 'rei arturo', 'king arturo'],
    nivel: 'intermediario',
    clubes: ['colo-colo', 'bayer-leverkusen', 'juventus', 'bayern', 'barcelona', 'inter', 'flamengo'],
    dica: 'Foi campeão nacional na Itália, na Alemanha e na Espanha, e ganhou dois títulos continentais seguidos com a seleção do seu país.',
  },
  {
    id: 'dzeko',
    nome: 'Edin Džeko',
    apelidos: ['dzeko', 'edin dzeko'],
    nivel: 'intermediario',
    clubes: ['wolfsburg', 'manchester-city', 'roma', 'inter', 'fenerbahce', 'fiorentina', 'schalke'],
    dica: 'É o maior artilheiro da história de uma seleção dos Bálcãs e ganhou o apelido de Diamante na terra onde nasceu.',
  },
  {
    id: 'hulk',
    nome: 'Hulk',
    apelidos: ['hulk', 'givanildo vieira de sousa', 'givanildo'],
    nivel: 'intermediario',
    clubes: ['vitoria', 'kawasaki-frontale', 'tokyo-verdy', 'porto', 'zenit', 'shanghai-sipg', 'atletico-mg'],
    dica: 'O apelido veio da força física, e a perna esquerda dele já estufou rede em quatro continentes.',
  },
  {
    id: 'coutinho',
    nome: 'Philippe Coutinho',
    apelidos: ['coutinho', 'philippe coutinho', 'philippe coutinho correia'],
    nivel: 'intermediario',
    clubes: ['vasco', 'inter', 'espanyol', 'liverpool', 'barcelona', 'bayern', 'aston-villa'],
    dica: 'Emprestado, marcou dois gols contra o clube que detinha seus direitos numa goleada histórica de oito a dois.',
  },
  {
    id: 'douglas-costa',
    nome: 'Douglas Costa',
    apelidos: ['douglas costa', 'douglas costa de souza'],
    nivel: 'intermediario',
    clubes: ['gremio', 'shakhtar', 'bayern', 'juventus', 'la-galaxy', 'fluminense'],
    dica: 'Ponta veloz de drible curto, recebeu uma das suspensões mais longas do futebol italiano por cuspir num adversário.',
  },
  {
    id: 'riquelme',
    nome: 'Juan Román Riquelme',
    apelidos: ['riquelme', 'juan roman riquelme', 'roman'],
    nivel: 'intermediario',
    clubes: ['boca-juniors', 'barcelona', 'villarreal'],
    dica: 'Último dos camisas 10 lentos e geniais, perdeu um pênalti nos acréscimos de uma semifinal de Champions.',
  },
  {
    id: 'everton-ribeiro',
    nome: 'Everton Ribeiro',
    apelidos: ['everton ribeiro', 'everton augusto de barros ribeiro'],
    nivel: 'intermediario',
    clubes: ['corinthians', 'coritiba', 'cruzeiro', 'al-ahli-saudi', 'flamengo', 'bahia'],
    dica: 'Foi eleito o melhor jogador do Brasileirão em dois anos seguidos por um clube mineiro antes de virar ídolo no Rio.',
  },
  {
    id: 'thiago-silva',
    nome: 'Thiago Silva',
    apelidos: ['thiago silva', 'monstro'],
    nivel: 'intermediario',
    clubes: ['fluminense', 'porto', 'milan', 'psg', 'chelsea'],
    dica: 'Quase teve a carreira encerrada por uma tuberculose contraída na Rússia, e virou capitão da seleção mais de dez anos depois.',
  },
  {
    id: 'firmino',
    nome: 'Roberto Firmino',
    apelidos: ['firmino', 'roberto firmino', 'bobby firmino'],
    nivel: 'intermediario',
    clubes: ['figueirense', 'hoffenheim', 'liverpool', 'al-ahli-saudi'],
    dica: 'Falso nove de um trio de ataque temido na Inglaterra, ficou famoso pelo sorriso e pelos gols de calcanhar.',
  },
  {
    id: 'otamendi',
    nome: 'Nicolás Otamendi',
    apelidos: ['otamendi', 'nicolas otamendi'],
    nivel: 'intermediario',
    clubes: ['velez-sarsfield', 'porto', 'valencia', 'manchester-city', 'benfica'],
    dica: 'Zagueiro durão e de carrinho pesado, só foi campeão continental e mundial pela seleção já passando dos trinta.',
  },

  // ==================================================================
  // DIFÍCIL — carreira errante ou nome que o tempo apagou
  // ==================================================================
  {
    id: 'adriano',
    nome: 'Adriano Imperador',
    apelidos: ['adriano', 'adriano imperador', 'imperador', 'adriano leite ribeiro'],
    nivel: 'dificil',
    clubes: ['flamengo', 'inter', 'fiorentina', 'parma', 'sao-paulo', 'roma', 'corinthians', 'athletico-pr', 'atletico-mg'],
    dica: 'Tinha o chute mais forte da Itália e virou nota máxima num videogame; a morte do pai mudou o rumo de tudo.',
  },
  {
    id: 'vagner-love',
    nome: 'Vágner Love',
    apelidos: ['vagner love', 'love', 'vagner silva de souza'],
    nivel: 'dificil',
    clubes: ['palmeiras', 'cska-moscow', 'flamengo', 'shandong-luneng', 'corinthians', 'besiktas', 'monaco', 'sport'],
    dica: 'Virou ídolo improvável no frio de Moscou, onde foi artilheiro e levantou uma taça europeia.',
  },
  {
    id: 'jo',
    nome: 'Jô',
    apelidos: ['jo', 'joao alves de assis silva'],
    nivel: 'dificil',
    clubes: ['corinthians', 'cska-moscow', 'manchester-city', 'everton', 'galatasaray', 'internacional', 'atletico-mg', 'nagoya-grampus'],
    dica: 'Foi artilheiro do Brasileirão e convocado para uma Copa depois de uma década de idas e vindas frustradas pela Europa.',
  },
  {
    id: 'nilmar',
    nome: 'Nilmar',
    apelidos: ['nilmar', 'nilmar honorato da silva'],
    nivel: 'dificil',
    clubes: ['internacional', 'corinthians', 'lyon', 'villarreal', 'santos'],
    dica: 'Foi anunciado como a grande promessa gaúcha do ataque, brilhou no submarino espanhol e as lesões cobraram o resto.',
  },
  {
    id: 'pato',
    nome: 'Alexandre Pato',
    apelidos: ['pato', 'alexandre pato', 'alexandre rodrigues da silva'],
    nivel: 'dificil',
    clubes: ['internacional', 'milan', 'corinthians', 'sao-paulo', 'villarreal', 'orlando-city'],
    dica: 'Chegou à Itália aos dezessete como o novo fenômeno; um pênalti cavado e perdido num clássico virou o símbolo da queda.',
  },
  {
    id: 'bendtner',
    nome: 'Nicklas Bendtner',
    apelidos: ['bendtner', 'nicklas bendtner', 'lord bendtner'],
    nivel: 'dificil',
    clubes: ['arsenal', 'birmingham-city', 'sunderland', 'juventus', 'wolfsburg', 'nottingham-forest', 'rosenborg', 'copenhagen'],
    dica: 'Dinamarquês que se declarou publicamente entre os melhores do mundo e ficou mais famoso pela cueca da comemoração.',
  },
  {
    id: 'quaresma',
    nome: 'Ricardo Quaresma',
    apelidos: ['quaresma', 'ricardo quaresma'],
    nivel: 'dificil',
    clubes: ['sporting-cp', 'barcelona', 'porto', 'inter', 'chelsea', 'besiktas', 'vitoria-guimaraes'],
    dica: 'A trivela era a marca registrada, e a sombra de um compatriota maior o transformou no eterno talento desperdiçado.',
  },
  {
    id: 'balotelli',
    nome: 'Mario Balotelli',
    apelidos: ['balotelli', 'mario balotelli', 'super mario'],
    nivel: 'dificil',
    clubes: ['inter', 'manchester-city', 'milan', 'liverpool', 'nice', 'marseille', 'brescia', 'monza'],
    dica: 'Levantou a camisa perguntando por que sempre ele, e antes disso quase incendiou a própria casa com fogos de artifício.',
  },
  {
    id: 'keirrison',
    nome: 'Keirrison',
    apelidos: ['keirrison', 'keirrison de souza carneiro'],
    nivel: 'intermediario',
    clubes: ['coritiba', 'palmeiras', 'barcelona', 'benfica', 'fiorentina', 'santos', 'cruzeiro', 'coritiba', 'londrina', 'arouca'],
    dica: 'Foi artilheiro do Brasileirão e comprado por um gigante catalão, mas nunca chegou a entrar em campo por ele.',
  },
  {
    id: 'diego-tardelli',
    nome: 'Diego Tardelli',
    apelidos: ['diego tardelli', 'tardelli', 'diego tardelli martins'],
    nivel: 'dificil',
    clubes: ['sao-paulo', 'flamengo', 'real-betis', 'psv', 'atletico-mg', 'gremio', 'shandong-luneng', 'bahia'],
    dica: 'Marcou os dois gols de uma vitória brasileira sobre a Argentina e mesmo assim nunca se firmou na seleção.',
  },
  {
    id: 'elkeson',
    nome: 'Elkeson',
    apelidos: ['elkeson', 'ai kesen', 'elkeson de oliveira cardoso'],
    nivel: 'dificil',
    clubes: ['vitoria', 'botafogo', 'guangzhou-evergrande', 'shanghai-sipg', 'gremio'],
    dica: 'Foi o primeiro jogador sem qualquer ascendência local a ser naturalizado e convocado pela seleção da China.',
  },
  {
    id: 'rafael-sobis',
    nome: 'Rafael Sóbis',
    apelidos: ['rafael sobis', 'sobis'],
    nivel: 'dificil',
    clubes: ['internacional', 'real-betis', 'fluminense', 'cruzeiro'],
    dica: 'Foi campeão da Libertadores e do Mundial aos vinte e um anos por um clube gaúcho e nunca mais alcançou aquele patamar.',
  },
  {
    id: 'farfan',
    nome: 'Jefferson Farfán',
    apelidos: ['farfan', 'jefferson farfan', 'foquita'],
    nivel: 'dificil',
    clubes: ['psv', 'schalke', 'al-jazira', 'lokomotiv-moscow'],
    dica: 'Peruano veloz pelas pontas, foi peça da campanha que encerrou trinta e seis anos de ausência do seu país nas Copas.',
  },
  {
    id: 'denilson',
    nome: 'Denílson',
    apelidos: ['denilson', 'denilson de oliveira araujo'],
    nivel: 'dificil',
    clubes: ['sao-paulo', 'real-betis', 'flamengo', 'bordeaux', 'al-nassr', 'palmeiras'],
    dica: 'Virou o jogador mais caro do mundo em 1998 por causa de um drible em série que quase nunca terminava em gol.',
  },
  {
    id: 'drenthe',
    nome: 'Royston Drenthe',
    apelidos: ['drenthe', 'royston drenthe'],
    nivel: 'dificil',
    clubes: ['feyenoord', 'real-madrid', 'hercules', 'everton', 'reading', 'sheffield-wednesday', 'kayserispor'],
    dica: 'Eleito o melhor de um Europeu sub-21, virou rapper e rodou mais de dez clubes depois de passar por Madrid.',
  },
]
